# -*- coding: utf-8 -*-
"""
Generate Top 100 Landmark Artistic, Musical, Architectural & Cultural Milestones (Ancient to Modern)
Covers Western Art/Music, Korean Art/Music, Chinese & Global Masterpieces.
"""

import json
import os

ART_100 = [
    # --- Ancient & Classical Art & Music (BC ~ 5th Century) ---
    {"id": "art-001-lascaux-cave-paintings", "title": "라스코 동굴 벽화와 후기 구석기 미술의 탄생", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -15000, "year_end": -13000, "summary": "프랑스 라스코 동굴에 붉은 황토와 숯으로 야생 들소, 사슴, 말의 역동적인 움직임을 사실적으로 묘사.", "historical_significance": "인류 회화 예술의 기원이자 주술적 생명력 표현의 걸작."},
    {"id": "art-002-epic-of-gilgamesh", "title": "메소포타미아 『길가메시 서사시』 (인류 최초의 서사시)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -2100, "year_end": -1200, "summary": "우루크의 왕 길가메시가 친구 엔키두의 죽음 후 영생의 약초를 찾아 떠나는 여정을 쐐기문자 점토판에 기록.", "historical_significance": "세계 문학사상 가장 오래된 대서사시이자 대홍수 신화의 원형."},
    {"id": "art-003-homer-iliad-odyssey", "title": "호메로스의 2대 서사시 『일리아스』와 『오디세이아』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -800, "year_end": -750, "summary": "트로이 전쟁의 영웅 아킬레우스의 분노와 오디세우스의 10년간의 귀향 모험을 운문 서사시로 노래.", "historical_significance": "서양 고전문학과 신화, 그리스 비극의 영원한 원천."},
    {"id": "art-004-parthenon-temple-athens", "title": "아테네 아크로폴리스 파르테논 신전 완공 (익티노스·페이디아스)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -447, "year_end": -432, "summary": "황금비율(1:1.618)과 엔타시스(배흘림 기법), 착시 교정 기법을 적용한 도리스식 대리석 아테나 신전.", "historical_significance": "서양 고전주의 건축 미학의 절대적 표준."},
    {"id": "art-005-greek-tragedy-sophocles-oedipus", "title": "소포클레스의 비극 『오이디푸스 왕』 상연", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -429, "year_end": -429, "summary": "자신의 운명을 피하려다 아버지를 죽이고 어머니와 혼인한 테베 왕의 비극적 운명과 카타르시스(정화)를 그린 희곡.", "historical_significance": "서양 연극과 드라마 예술의 최고 정점."},
    {"id": "art-006-shijing-classic-of-poetry", "title": "동양 최초의 시가 총집 『시경(詩經)』 편찬", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": -600, "year_end": -500, "summary": "주나라의 민요(국풍), 궁중 음악(아), 제사 음악(송) 305편을 공자가 산정·정리한 시가집.", "historical_significance": "동아시아 낭만주의 및 현실주의 서정시의 시조."},
    {"id": "art-007-qu-yuan-chu-ci-lisao", "title": "굴원의 초사 『이소(離騷)』와 남방 낭만주의 문학", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": -340, "year_end": -278, "summary": "초나라 시인 굴원이 나라를 걱정하며 신화와 상상력을 결합한 373구의 웅장한 서정시 창작.", "historical_significance": "단오절(멱라수)의 유래이자 북방 시경과 대비되는 남방 문학의 최고봉."},
    {"id": "art-008-terracotta-army-sculpture", "title": "진시황릉 병마용갱(Terracotta Army)의 대규모 사실주의 조각", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": -246, "year_end": -208, "summary": "얼굴 표정과 복식, 머리 모양이 모두 다른 실물 크기 8,000여 구의 점토 군사·군마 조각상 군단.", "historical_significance": "고대 동양의 경이로운 사실주의 군상 조각 기술 증명."},
    {"id": "art-009-venus-de-milo-sculpture", "title": "밀로의 비너스(아프로디테) 대리석 조각상 제작", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -130, "year_end": -100, "summary": "밀로스섬에서 발견된 고전적 단아함과 헬레니즘의 관능미, 8등신 황금비율이 완벽하게 결합된 대리석 누드상.", "historical_significance": "서양 미술에서 여성의 인체 미학을 대표하는 불멸의 조각."},
    {"id": "art-010-laocoon-and-his-sons", "title": "헬레니즘 조각의 극치 『라오콘 군상(Laocoön and His Sons)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": -50, "year_end": 50, "summary": "트로이 사제 라오콘과 두 아들이 바다뱀에게 휘감겨 고통스럽게 절규하는 순간의 근육과 표정을 극적으로 묘사.", "historical_significance": "르네상스 미켈란젤로에게 결정적 영감을 준 역동적 조각의 걸작."},
    {"id": "art-011-colosseum-amphitheatre-rome", "title": "로마 콜로세움(플라비우스 원형극장) 완공", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 70, "year_end": 80, "summary": "5만 명을 수용할 수 있는 4층 구조의 거대 타원형 극장으로 도리스·이오니아·코린트 양식 기둥과 아치 결합.", "historical_significance": "고대 로마 콘크리트 공학과 대중 엔터테인먼트 건축의 정점."},
    {"id": "art-012-danyu-semungyeong-mirror", "title": "한국 국보 다뉴세문경(정문경)의 초정밀 청동 기하학 주조", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": -400, "year_end": -300, "summary": "직경 21cm 거울 뒷면에 0.3mm 간격의 미세한 동심원과 삼각선 13,000개를 새긴 청동 거울.", "historical_significance": "고대 동아시아 최고의 금속 공예 미술품."},
    {"id": "art-013-wang-xizhi-lantingji-xu", "title": "서성(書聖) 왕희지의 『난정집서(蘭亭集序)』 행서체 완성", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 353, "year_end": 353, "summary": "324자의 글자 중 '갈 지(之)'자 20자가 모두 다른 변화무쌍한 필치를 선보인 '천하제일행서'.", "historical_significance": "동양 서예를 독자적 순수 예술로 승격시킨 최고 걸작."},
    {"id": "art-014-gu-kaizhi-nushi-zhen-tu", "title": "고개지의 『여사잠도(女史箴圖)』와 춘잠토사 선묘화", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 380, "year_end": 405, "summary": "누에고치에서 실을 뽑아내듯 유려하고 끊어지지 않는 철선묘로 궁중 여인들의 자태를 묘사한 인물화.", "historical_significance": "중국 전통 회화의 '이형전신(형상으로 정신을 전함)' 미학의 원조."},
    {"id": "art-015-goguryeo-tomb-murals-muyongchong", "title": "고구려 무용총·수렵도 고분 벽화 프레스코 완성", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 400, "year_end": 500, "summary": "달리는 말 위에서 뒤를 돌아보며 활을 쏘는 파르티안 샷(개마총)과 웅장한 수렵도, 가무 무용도 채색 벽화.", "historical_significance": "고구려의 호방한 기상과 동아시아 고대 회화의 최고 걸작(세계유산)."},

    # --- Medieval, Byzantine & Golden Age Masterpieces (6th ~ 14th Century) ---
    {"id": "art-016-hagia-sophia-byzantine-mosaic", "title": "콘스탄티노폴리스 하기아 소피아 대성당과 황금 모자이크", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 537, "year_end": 560, "summary": "빛이 쏟아지는 거대한 펜던티브 돔과 유리·금박 테세라를 이용한 그리스도 판토크라토르 모자이크 예술.", "historical_significance": "비잔틴 제국 기독교 예술과 건축 공학의 최고봉."},
    {"id": "art-017-gregorian-chant-codification", "title": "교황 그레고리우스 1세의 그레고리오 성가(Gregorian Chant) 집대성", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 590, "year_end": 604, "summary": "반주 없는 단선율(Monophony) 라틴어 전례 찬트를 수집·체계화하고 네우마(Neume) 악보 표기법의 기초 마련.", "historical_significance": "서양 클래식 음악과 오선보 기보법의 모태."},
    {"id": "art-018-baekje-gilt-bronze-incense-burner", "title": "백제 금동대향로(국보) 주조", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 550, "year_end": 600, "summary": "용 받침대 위에 연꽃과 74개 봉우리, 신선, 악사 5명, 동물 39마리를 완벽한 비례로 조각한 61.8cm 대향로.", "historical_significance": "백제 금속 공예 미술의 정점이자 도교와 불교 사상의 완벽한 융합."},
    {"id": "art-019-bulguksa-seokguram-buddha", "title": "통일신라 석굴암 본존불과 불국사 석조 건축 (김대성)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 751, "year_end": 774, "summary": "백색 화강암 인공 돔 석굴에 3.5m 크기의 완벽한 황금비율 본존불과 십대제자 부조 조각 완성(유네스코 세계유산).", "historical_significance": "동양 불교 조각사상 가장 자비롭고 완벽한 비례를 갖춘 최고 걸작."},
    {"id": "art-020-li-bai-du-fu-tang-poetry", "title": "이백과 두보의 당시(唐詩) 문학의 황금기", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 730, "year_end": 770, "summary": "시선(詩仙) 이백의 초월적 낭만주의와 시성(詩聖) 두보의 엄격한 율시(칠언율시)와 애민 사실주의 시편 집대성.", "historical_significance": "동양 서정 문학의 영원한 최고봉."},
    {"id": "art-021-goryeo-sangam-celadon-vase", "title": "고려 상감청자(청자상감운학문매병)의 비색 공예 완성", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1150, "year_end": 1200, "summary": "구름 사이를 날아오르는 69마리의 학을 흑백 상감으로 새기고 비취색 비색 유약을 입힌 고려 대표 국보 매병.", "historical_significance": "송나라 사신 서긍도 『고려도경』에서 '천하제일'로 극찬한 세계적 도예 걸작."},
    {"id": "art-022-bayeux-tapestry-embroidery", "title": "바이외 태피스트리(Bayeux Tapestry) 70m 자수 서사화", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1070, "year_end": 1080, "summary": "노르만 정복과 헤이스팅스 전투, 핼리 혜성을 양모 실로 수놓은 70m 길이의 아마포 두루마리 자수.", "historical_significance": "중세 시각 예술과 역사 기록화의 최고 걸작(유네스코 세계기록유산)."},
    {"id": "art-023-notre-dame-gothic-cathedral", "title": "파리 노트르담 대성당 완공과 고딕 스테인드글라스 (장미창)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1163, "year_end": 1250, "summary": "플라잉 버트레스와 리브 볼트로 벽을 허물고 거대한 원형 장미창 스테인드글라스를 통해 천상의 빛을 구현.", "historical_significance": "중세 서유럽 고딕 건축 예술의 최고 상징."},
    {"id": "art-024-zhang-zeduan-along-the-river", "title": "장택단의 『청명상하도(淸明上河圖)』 두루마리 풍속화", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1101, "year_end": 1125, "summary": "북송 수도 변경의 번화한 홍교 다리, 낙타 상단, 운하 배, 주막, 814명의 인물을 세밀화로 포착한 5.28m 명화.", "historical_significance": "중국 회화사상 가장 위대한 도시 풍속 기록 예술."},
    {"id": "art-025-dante-divine-comedy-poem", "title": "단테 알리기에리의 서사시 『신곡(La Divina Commedia)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1308, "year_end": 1320, "summary": "지옥(Inferno), 연옥(Purgatorio), 천국(Paradiso)을 3운구법(Terza Rima) 이탈리아 속어로 순례하는 대작.", "historical_significance": "중세 기독교 세계관의 총결산이자 르네상스 문학의 출발점."},
    {"id": "art-026-giotto-arena-chapel-frescoes", "title": "조토 디 본도네의 아레나 예배당 프레스코화 (르네상스 미술의 효시)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1305, "year_end": 1305, "summary": "평면적 중세 이콘을 벗어나 인물의 감정(유다의 입맞춤, 애도)과 3차원 공간 입체감을 최초로 표현.", "historical_significance": "서양 회화에 사실주의와 인간미를 불어넣은 근대 미술의 아버지."},

    # --- Renaissance to Baroque (15th ~ 17th Century) ---
    {"id": "art-027-brunelleschi-florence-dome", "title": "브루넬레스키의 피렌체 두오모 돔(Dome) 완공", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1420, "year_end": 1436, "summary": "목재 지지대 없이 이중 껍질 구조와 생선뼈 벽돌 쌓기로 직경 45m 거대 돔 완공 및 선원근법 발명.", "historical_significance": "르네상스 건축 공학과 원근법 회화 이론의 탄생."},
    {"id": "art-028-jan-van-eyck-arnolfini-portrait", "title": "얀 반 에이크의 『아르놀피니 부부의 초상』과 유화 기법 혁신", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1434, "year_end": 1434, "summary": "린시드 오일을 안료와 섞은 유화 물감을 최초로 완성하여 볼록거울 반사, 샹들리에 금속 광택의 극사실적 질감 묘사.", "historical_significance": "북유럽 르네상스 유화(Oil Painting) 기법의 완성자."},
    {"id": "art-029-botticelli-birth-of-venus", "title": "산드로 보티첼리의 『비너스의 탄생(The Birth of Venus)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1485, "year_end": 1485, "summary": "바다 거품에서 조개껍데기를 타고 태어난 사랑과 미의 여신 비너스를 신플라톤주의 미학으로 묘사한 템페라화.", "historical_significance": "기독교 주제를 넘어 고대 그리스 신화를 부활시킨 르네상스 명작."},
    {"id": "art-030-da-vinci-mona-lisa-last-supper", "title": "레오나르도 다 빈치의 『모나리자』와 『최후의 만찬』 (스푸마토 기법)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1495, "year_end": 1506, "summary": "윤곽선을 안개처럼 부드럽게 흐리는 스푸마토 기법과 심리적 긴장감을 투시원근법으로 포착한 신비한 미소의 초상화.", "historical_significance": "인류 역사상 가장 유명한 회화이자 르네상스 천재 예술의 상징."},
    {"id": "art-031-michelangelo-david-and-sistine", "title": "미켈란젤로의 『다비드상』 및 시스티나 성당 천장화 『천지창조』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1501, "year_end": 1512, "summary": "5.17m 거대한 대리석 조각 다비드상과 시스티나 성당 천장에 『아담의 창조』를 포함한 300여 명의 웅장한 인체 프레스코 완성.", "historical_significance": "조각과 회화에서 인체 해부학적 완벽성과 신적 영감을 구현한 거장."},
    {"id": "art-032-raphael-school-of-athens", "title": "라파엘로 산치오의 바티칸 궁전 벽화 『아테네 학당』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1509, "year_end": 1511, "summary": "하늘을 가리키는 플라톤과 땅을 가리키는 아리스토텔레스를 중심으로 고대 50여 명의 철학자를 완벽한 아치 원근법 안에 배치.", "historical_significance": "르네상스 고전주의 균형과 조화의 최고 걸작."},
    {"id": "art-033-an-gyeon-dream-journey-peach-blossom", "title": "안견의 『몽유도원도(夢遊桃源圖)』 (안평대군의 꿈)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1447, "year_end": 1447, "summary": "안평대군이 꾼 무릉도원 꿈을 사흘 만에 웅장한 필치로 화폭에 담은 조선 전기 산수화의 최고 국보급 걸작.", "historical_significance": "조선 초기 독창적인 관념 산수화의 최고봉."},
    {"id": "art-034-shakespeare-four-great-tragedies", "title": "윌리엄 셰익스피어의 4대 비극 (『햄릿』, 『오셀로』, 『리어왕』, 『맥베스』)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1600, "year_end": 1606, "summary": "'죽느냐 사느냐 그것이 문제로다' 등 인간의 우유부단, 질투, 오만, 야망의 파멸을 운문과 산문 희곡으로 완성.", "historical_significance": "세계 문학사상 가장 위대한 극작가이자 영어 어휘의 대혁신."},
    {"id": "art-035-cervantes-don-quixote-novel", "title": "미겔 데 세르반테스의 『돈키호테(Don Quixote)』 (최초의 근대 소설)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1605, "year_end": 1615, "summary": "기사도 소설에 빠져 풍차를 거인으로 착각해 돌진하는 돈키호테와 현실적인 산초 판사의 풍자 모험담.", "historical_significance": "서양 최초의 근대 리얼리즘 소설이자 세계 문학의 불멸의 고전."},
    {"id": "art-036-caravaggio-chiaroscuro-baroque", "title": "카라바조의 강렬한 명암대조법(테네브리즘)과 바로크 미술 탄생", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1599, "year_end": 1605, "summary": "『성 마태오의 소명』 등에서 칠흑 같은 어둠 속에 한 줄기 빛을 던져 인물의 긴장감과 연극적 사실주의를 극대화.", "historical_significance": "바로크 회화의 시조이자 렘브란트, 벨라스케스에게 결정적 영향."},
    {"id": "art-037-bernini-ecstasy-of-saint-teresa", "title": "잔 로렌초 베르니니의 『성 테레사의 환희』 대리석 조각", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1647, "year_end": 1652, "summary": "천사의 화살을 맞고 신의 사랑에 도취된 성녀의 황홀경과 옷자락의 격정적 주름을 대리석으로 역동적으로 조각.", "historical_significance": "바로크 조각의 최고 정점이자 극장식 공간 연출의 걸작."},
    {"id": "art-038-rembrandt-the-night-watch", "title": "렘브란트 판 레인의 『야간 순찰(The Night Watch)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1642, "year_end": 1642, "summary": "정적인 단체 초상화 관습을 깨고 출동하는 암스테르담 민병대원들의 순간적 움직임과 빛의 마법을 4m 대화폭에 담음.", "historical_significance": "네덜란드 황금시대 회화의 최고 걸작이자 빛의 화가 렘브란트의 대표작."},
    {"id": "art-039-velazquez-las-meninas", "title": "디에고 벨라스케스의 『시녀들(Las Meninas)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1656, "year_end": 1656, "summary": "마르가리타 공주와 시녀들, 거울 속 국왕 부부, 그림을 그리는 화가 자신을 다층적 시선과 공간 구성으로 배치.", "historical_significance": "미술사학자 푸코가 격찬한 회화 속 시선과 재현의 철학적 최고 걸작."},
    {"id": "art-040-vermeer-girl-with-pearl-earring", "title": "요하네스 베르메르의 『진주 귀걸이를 한 소녀』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1665, "year_end": 1665, "summary": "청금석(울트라마린) 터번을 두르고 돌아보는 소녀의 촉촉한 입술과 빛나는 진주 귀걸이를 섬세한 빛으로 포착.", "historical_significance": "'북유럽의 모나리자'로 불리는 네덜란드 델프트 화파의 보물."},
    {"id": "art-041-monteverdi-opera-lorfeo", "title": "클라우디오 몬테베르디의 오페라 『오르페오(L'Orfeo)』 (최초의 걸작 오페라)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1607, "year_end": 1607, "summary": "오르페우스 신화를 바탕으로 독창(레치타티보·아리아), 합창, 40인조 오케스트라 서곡을 유기적으로 결합.", "historical_significance": "현대적 종합 오페라(Opera) 장르의 확립자."},

    # --- 18th & 19th Century (Baroque, Classical, Romantic, Impressionism) ---
    {"id": "art-042-vivaldi-four-seasons-concertos", "title": "안토니오 비발디의 바이올린 협주곡 『사계(The Four Seasons)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1723, "year_end": 1725, "summary": "봄의 새소리, 여름의 폭풍, 가을의 수확, 겨울의 얼음판 미끄러짐을 표제 음악 형식의 독주 바이올린 협주곡으로 묘사.", "historical_significance": "바로크 협주곡(Concerto)의 대중적 최고 명작."},
    {"id": "art-043-bach-st-matthew-passion-well-tempered", "title": "요한 제바스티안 바흐의 『마태 수난곡』 및 『평균율 클라비어곡집』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1722, "year_end": 1727, "summary": "대위법(푸가)과 화성학을 총집대성하여 24개 조성을 모두 연주하는 건반 음악의 구약성서 완성.", "historical_significance": "'음악의 아버지' 바흐에 의한 서양 다성음악의 최고봉."},
    {"id": "art-044-handel-messiah-hallelujah", "title": "게오르크 프리드리히 헨델의 오라토리오 『메시아(Messiah)』와 할렐루야", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1741, "year_end": 1742, "summary": "그리스도의 탄생, 수난, 부활을 노래한 대규모 오라토리오로 국왕 조지 2세가 기립한 '할렐루야' 합창 수록.", "historical_significance": "종교 합창 음악의 불멸의 기념비."},
    {"id": "art-045-jeong-seon-inwang-jesaekdo", "title": "겸재 정선의 진경산수화 『인왕제색도』와 『금강전도』", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1751, "year_end": 1751, "summary": "비 온 뒤 안개 갠 인왕산의 묵직한 바위산 암벽을 대담한 먹물 번짐(적묵법)으로 사생한 국보 제216호.", "historical_significance": "중국 산수화 모방을 탈피한 조선 고유의 독창적 진경산수화 완성."},
    {"id": "art-046-kim-hongdo-genre-paintings", "title": "단원 김홍도의 풍속화첩 『단원풍속도첩』 (씨름·서당·타작)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1775, "year_end": 1790, "summary": "역동적인 굵은 필선과 해학적인 구도로 조선 서민들의 생생한 노동과 놀이 문화를 묘사한 보물 화첩.", "historical_significance": "조선 후기 서민 문화 부흥을 상징하는 민족 풍속화의 최고봉."},
    {"id": "art-047-shin-yunbok-hyewon-genre-painting", "title": "혜원 신윤복의 『혜원전신첩』 (단오풍정·월하정인)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1780, "year_end": 1805, "summary": "섬세한 유려한 필선과 화려한 원색 채색으로 양반과 기녀의 풍류, 남녀의 은밀한 사랑을 묘사한 국보 화첩.", "historical_significance": "조선 후기 도시 유흥 문화와 여성 생활사를 담은 회화 걸작."},
    {"id": "art-048-cao-xueqin-dream-of-red-chamber", "title": "조설근의 장편 소설 『홍루몽(紅樓夢)』 편찬", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1750, "year_end": 1791, "summary": "가보옥과 임대옥의 비극적 사랑을 중심으로 청대 가문 귀족 사회의 성쇠를 유려한 필치로 묘사.", "historical_significance": "중국 4대 기서 중 최고의 걸작이자 세계적 고전 문학."},
    {"id": "art-049-mozart-marriage-of-figaro-requiem", "title": "볼프강 아마데우스 모차르트의 오페라 『피가로의 결혼』 및 『레퀴엠』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1786, "year_end": 1791, "summary": "천재적인 멜로디와 하모니로 귀족 풍자 오페라 『피가로의 결혼』, 『돈 조반니』와 미완의 유작 『레퀴엠』 작곡.", "historical_significance": "고전파 음악의 천재이자 서양 음악사상 가장 완벽한 멜로디 메이커."},
    {"id": "art-050-haydn-father-of-symphony", "title": "요제프 하이든의 교향곡 104곡 완성과 고전파 소나타 형식 확립", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1760, "year_end": 1795, "summary": "4악장 교향곡 형식과 현악 4중주 장르를 완성하여 『놀람 교향곡』, 『런던 교향곡』, 오라토리오 『천지창조』 작곡.", "historical_significance": "'교향곡의 아버지'이자 모차르트와 베토벤의 스승."},
    {"id": "art-051-goethe-faust-magnum-opus", "title": "요한 볼프강 폰 괴테의 희곡 『파우스트(Faust)』 (질풍노도 운동)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1775, "year_end": 1832, "summary": "메피스토펠레스에게 영혼을 건 파우스트 박사가 끊임없이 방황하며 진리를 탐구하는 60년간의 필생의 대작.", "historical_significance": "독일 고전문학의 최고봉이자 인류 영혼의 성찰록."},
    {"id": "art-052-beethoven-ninth-symphony-choral", "title": "루트비히 판 베토벤의 교향곡 9번 『합창(Choral)』 (환희의 송가)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1822, "year_end": 1824, "summary": "청력을 완전히 잃은 상태에서 실러의 시에 성악과 합창을 교향곡 역사상 최초로 결합하여 인류 화합과 자유를 노래.", "historical_significance": "서양 클래식 음악사상 가장 위대한 교향곡이자 유럽연합(EU) 공식 국가."},
    {"id": "art-053-delacroix-liberty-leading-the-people", "title": "외젠 들라크루아의 『민중을 이끄는 자유의 여신(1830년 7월 28일)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1830, "year_end": 1830, "summary": "삼색기를 들고 바리케이드를 넘는 자유의 여신 마리안느와 시민들의 투쟁을 역동적인 낭만주의 붓터치로 묘사.", "historical_significance": "프랑스 공화주의와 낭만주의 혁명 미술의 최고 상징."},
    {"id": "art-054-frederic-chopin-piano-nocturnes", "title": "프레데리크 쇼팽의 피아노 시학 (녹턴·발라드·영웅 폴로네즈)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1830, "year_end": 1849, "summary": "피아노의 음색을 극대화한 루바토 기법과 폴란드의 민족적 한(恨)을 서정적 피아노 곡으로 승화.", "historical_significance": "'피아노의 시인'으로 불리는 낭만주의 피아노 음악의 거장."},
    {"id": "art-055-gustave-courbet-realism-burial", "title": "귀스타브 쿠르베의 『오르낭의 매장』과 사실주의(Realism) 선언", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1849, "year_end": 1855, "summary": "'나에게 천사를 보여주면 천사를 그리겠다'며 신화나 영웅 대신 평범한 시골 촌부의 실제 장례식을 거대한 화폭에 그림.", "historical_significance": "미화된 고전주의를 깨부순 근대 사실주의 회화의 개막."},
    {"id": "art-056-victor-hugo-les-miserables", "title": "빅토르 위고의 대하소설 『레 미제라블(Les Misérables)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1862, "year_end": 1862, "summary": "빵 한 조각을 훔친 죄로 19년간 복역한 장발장의 구원과 1832년 6월 봉기 청년들의 자유 투쟁을 그린 인도주의 대작.", "historical_significance": "프랑스 문학사상 가장 사랑받는 사회 고발 및 사랑의 서사시."},
    {"id": "art-057-claude-monet-impression-sunrise", "title": "클로드 모네의 『인상, 일출(Impression, Sunrise)』과 인상주의의 탄생", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1872, "year_end": 1874, "summary": "르아브르 항구의 아침 햇살과 바다 물결에 반사되는 빛의 찰나적 인상을 원색의 거친 터치로 포착.", "historical_significance": "인상파(Impressionism)라는 이름을 낳은 현대 미술의 문을 연 명작."},
    {"id": "art-058-tchaikovsky-swan-lake-nutcracker", "title": "표트르 차이콥스키의 3대 발레 명곡 (『백조의 호수』, 『호두까기 인형』)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1876, "year_end": 1892, "summary": "화려한 오케스트레이션과 애절한 슬라브적 서정 선율로 고전 발레 음악을 독립된 예술 음악으로 격상.", "historical_significance": "러시아 낭만주의 클래식 음악과 발레의 세계적 정점."},
    {"id": "art-059-vincent-van-gogh-starry-night", "title": "빈센트 반 고흐의 『별이 빛나는 밤(The Starry Night)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1889, "year_end": 1889, "summary": "생레미 요양원 방에서 소용돌이치는 밤하늘의 은하수와 별빛, 사이프러스 나무를 두터운 임파스토 물감으로 격정적 표현.", "historical_significance": "후기 인상주의이자 표현주의 미술에 결정적 영향을 미친 불멸의 명화."},
    {"id": "art-060-auguste-rodin-the-thinker-gates-of-hell", "title": "오귀스트 로댕의 조각 『생각하는 사람』과 『지옥의 문』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1880, "year_end": 1904, "summary": "단테의 신곡에서 영감을 받아 웅크리고 고뇌하는 인간의 근육과 내면의 번뇌를 청동 조각으로 형상화.", "historical_significance": "근대 조각의 아버지 로댕의 대표 걸작."},
    {"id": "art-061-edvard-munch-the-scream", "title": "에드바르 뭉크의 『절규(The Scream)』와 표현주의(Expressionism)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1893, "year_end": 1893, "summary": "피빛으로 물든 노을 하늘 아래 귀를 막고 비명을 지르는 해골 형상의 인물을 통해 현대인의 실존적 불안을 시각화.", "historical_significance": "20세기 표현주의 미술의 대표 아이콘."},
    {"id": "art-062-pansori-twelve-madang-korea", "title": "조선 판소리 12마당의 집대성과 신재효의 판소리 사설 정립", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1860, "year_end": 1884, "summary": "춘향가, 심청가, 흥보가, 수궁가, 적벽가 등 구전 판소리 사설을 6마당으로 정리하고 여류 명창(진채선) 육성.", "historical_significance": "유네스코 인류무형문화유산으로 등재된 한국 고유의 종합 성악 예술."},

    # --- 20th & 21st Century (Modernism, Contemporary Art, Cinema & K-Culture) ---
    {"id": "art-063-pablo-picasso-les-demoiselles-guernica", "title": "파블로 피카소의 『아비뇽의 처녀들』(1907)과 『게르니카』(1937, 입체파)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1907, "year_end": 1937, "summary": "원근법을 파괴하고 대상을 다시점 입체로 해체·재조합한 큐비즘 창시 및 나치의 스페인 폭격을 고발한 『게르니카』 제작.", "historical_significance": "20세기 미술사 최대의 혁명가 피카소의 불멸의 걸작."},
    {"id": "art-064-henri-matisse-the-dance-fauvism", "title": "앙리 마티스의 『춤(The Dance)』과 야수파(Fauvism)의 색채 해방", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1909, "year_end": 1910, "summary": "붉은 원색의 나체 인물들이 손을 잡고 원을 그리며 춤추는 모습을 강렬한 평면 색채로 표현.", "historical_significance": "형태의 재현을 벗어나 원색의 순수한 감정을 폭발시킨 야수파의 거장."},
    {"id": "art-065-wassily-kandinsky-abstract-art", "title": "바실리 칸딘스키의 최초의 순수 추상 수채화 (추상미술의 탄생)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1910, "year_end": 1911, "summary": "구체적인 대상을 완전히 지우고 점·선·면과 색채의 리듬만으로 음악적 영혼의 울림을 표현한 『예술에서의 정신적인 것에 대하여』 출간.", "historical_significance": "현대 추상미술(Abstract Art)의 창시자."},
    {"id": "art-066-marcel-duchamp-fountain-dadaism", "title": "마르셀 뒤샹의 『샘(Fountain, 1917년)』과 개념미술(레디메이드)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1917, "year_end": 1917, "summary": "남성용 소변기에 'R. Mutt'라고 서명하여 전시장(뉴욕 독립미술가전)에 출품함으로써 '예술이란 손으로 만드는 것이 아니라 선택하는 개념'임을 선언.", "historical_significance": "현대 개념미술과 다다이즘의 혁명적 분기점."},
    {"id": "art-067-piet-mondrian-composition-de-stijl", "title": "피트 몬드리안의 기하학적 신조형주의 『빨강, 파랑, 노랑의 구성』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1921, "year_end": 1930, "summary": "검은 수평·수직 격자선과 3원색(빨강, 파랑, 노랑), 무채색 면만으로 우주의 절대적 질서와 균형을 표현(더 스테일).", "historical_significance": "현대 미니멀리즘 디자인과 바우하우스 건축에 지대한 영향."},
    {"id": "art-068-salvador-dali-persistence-of-memory", "title": "살바도르 달리의 초현실주의 『기억의 지속(녹아내리는 시계)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1931, "year_end": 1931, "summary": "나뭇가지와 해변에 흐물흐물하게 녹아내리는 시계들과 꿈속 무의식의 환상을 정밀한 사실적 기법으로 묘사.", "historical_significance": "초현실주의(Surrealism) 미술의 가장 대표적인 아이콘."},
    {"id": "art-069-igor-stravinsky-rite-of-spring", "title": "이고르 스트라빈스키의 발레 음악 『봄의 제전(The Rite of Spring)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1913, "year_end": 1913, "summary": "파리 초연 당시 파격적인 원시주의 불협화음과 변박자 리듬으로 객석에서 관객들의 격렬한 폭동을 유발.", "historical_significance": "20세기 현대 음악(모더니즘)의 문을 연 기념비적 명곡."},
    {"id": "art-070-charlie-chaplin-modern-times-cinema", "title": "찰리 채플린의 무성영화 걸작 『모던 타임즈(Modern Times)』 (1936년)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1936, "year_end": 1936, "summary": "공장의 톱니바퀴에 끼어 나사를 조이는 노동자 찰리를 통해 산업 자본주의의 인간 소외를 눈물겨운 슬랩스틱 코미디로 풍자.", "historical_significance": "영화 예술사상 최고의 사회 풍자 영화이자 클래식 명작."},
    {"id": "art-071-george-gershwin-rhapsody-in-blue", "title": "조지 거슈윈의 『랩소디 인 블루(Rhapsody in Blue)』 (재즈와 클래식 융합)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1924, "year_end": 1924, "summary": "클라리넷의 미끄러지는 글리산도로 시작하여 미국 흑인 재즈 리듬과 서양 교향악 오케스트라를 완벽하게 결합.", "historical_significance": "미국 고유의 심포닉 재즈 음악 장르 창시."},
    {"id": "art-072-jackson-pollock-action-painting", "title": "잭슨 폴록의 액션 페인팅(Action Painting)과 추상표현주의", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1947, "year_end": 1950, "summary": "바닥에 캔버스를 펼쳐놓고 에나멜 페인트를 흩뿌리고 흘리는 드립 페인팅(Drip painting) 기법으로 전면 균일 회화(All-over) 완성.", "historical_significance": "세계 현대 미술의 중심지를 파리에서 뉴욕으로 이동시킨 주역."},
    {"id": "art-073-andy-warhol-pop-art-campbell", "title": "앤디 워홀의 팝아트(Pop Art)와 『캠벨 수프 캔』·『마릴린 먼로』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1962, "year_end": 1964, "summary": "실크스크린 기법으로 대량 생산 소비 상품과 대중 스타 이미지를 복제하여 고급 예술과 대중문화의 경계를 허묾.", "historical_significance": "20세기 후반 팝아트 혁명의 교황."},
    {"id": "art-074-nam-june-paik-video-art-father", "title": "백남준의 비디오 아트(Video Art) 창시와 『다다익선』 (1988년)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1963, "year_end": 1988, "summary": "텔레비전 모니터와 비디오 신디사이저를 결합해 미디어 아트를 개척하고 국립현대미술관에 1,003대 TV 타워 『다다익선』 설치.", "historical_significance": "'비디오 아트의 창시자'이자 글로벌 미디어 아트의 독보적 거장."},
    {"id": "art-075-the-beatles-sgt-pepper-album", "title": "비틀즈(The Beatles)의 『Sgt. Pepper's Lonely Hearts Club Band』 (1967년)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1967, "year_end": 1967, "summary": "스튜디오 녹음 기술을 극대화하여 앨범 전체를 하나의 유기적 서사로 연결한 최초의 콘셉트 앨범.", "historical_significance": "대중 록 음악을 고급 예술의 경지로 끌어올린 대중음악 역사상 최고의 음반."},
    {"id": "art-076-michael-jackson-thriller-album", "title": "마이클 잭슨의 『Thriller』 앨범과 뮤직비디오 혁명 (1982년)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1982, "year_end": 1983, "summary": "역대 전 세계 음반 판매량 1위(7,000만 장)를 기록하고 문워크와 시네마틱 뮤직비디오로 MTV 시대를 연 '팝의 황제'.", "historical_significance": "인종 장벽을 허물고 20세기 글로벌 팝 음악의 최고 정점 달성."},
    {"id": "art-077-samuel-beckett-waiting-for-godot", "title": "사무엘 베케트의 부조리극 『고도를 기다리며(Waiting for Godot)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1952, "year_end": 1953, "summary": "오지 않는 '고도'를 하염없이 기다리는 두 방랑자 블라디미르와 에스트라공을 통해 현대인의 실존적 허무와 기다림을 묘사.", "historical_significance": "전통 서사를 파괴한 20세기 부조리 연극(Theater of the Absurd)의 최고봉."},
    {"id": "art-078-gabriel-garcia-marquez-macondo", "title": "가브리엘 가르시아 마르케스의 『백년 동안의 고독』 (마술적 사실주의)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1967, "year_end": 1967, "summary": "가상의 마을 마콘도에서 부엔디아 가문 7대의 흥망성쇠를 환상과 현실이 교차하는 마술적 리얼리즘(Magical Realism)으로 서술.", "historical_significance": "라틴아메리카 문학 붐을 전 세계에 알린 20세기 문학의 걸작."},
    {"id": "art-079-george-orwell-1984-dystopia", "title": "조지 오웰의 디스토피아 소설 『1984』 (빅 브라더)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1949, "year_end": 1949, "summary": "텔레스크린으로 모든 일상을 감시하는 전체주의 독재 국가 오세아니아와 언어 통제(신어), '빅 브라더'의 공포를 고발.", "historical_significance": "전체주의와 감시 사회를 경고한 20세기 최고 예언적 정치 소설."},
    {"id": "art-080-miyazaki-hayao-spirited-away", "title": "미야자키 하야오의 애니메이션 『센과 치히로의 행방불명』 (2001년)", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2001, "year_end": 2001, "summary": "신들의 온천장에 들어간 소녀 치히로의 성장담을 통해 전통 자연관과 자본주의 비판을 수려한 수작업 작화로 완성(베를린 황금곰상).", "historical_significance": "세계 애니메이션 영화사상 최고의 예술적 성취."},
    {"id": "art-081-bong-joon-ho-parasite-oscars", "title": "봉준호 감독의 영화 『기생충(Parasite)』 칸 황금종려상 및 아카데미 4관왕", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2019, "year_end": 2020, "summary": "반지하 가족과 대저택 가족의 대비를 통해 현대 자본주의 계급 격차를 정교한 서스펜스와 블랙코미디로 연출(비영어권 영화 최초 작품상).", "historical_significance": "92년 오스카 역사상 최초의 외국어 영화 작품상 수상 및 세계 영화사 대기록."},
    {"id": "art-082-bts-billboard-hot-100-dynamite", "title": "방탄소년단(BTS)의 빌보드 핫100 1위 및 K-POP 글로벌 신드롬", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2020, "year_end": 2022, "summary": "『Dynamite』, 『Butter』 등으로 한국 가수 최초 빌보드 메인 싱글 차트 1위를 연속 달성하고 UN 총회 연설을 통해 청년 세대 위로.", "historical_significance": "K-POP이 아시아를 넘어 전 세계 팝 음악의 주류로 우뚝 선 문화적 쾌거."},
    {"id": "art-083-han-kang-nobel-literature-2024", "title": "소설가 한강의 한국인 최초 노벨문학상 수상 (2024년)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2016, "year_end": 2024, "summary": "『채식주의자』(맨부커상), 『소년이 온다』(5·18), 『작별하지 않는다』(제주 4·3)를 통해 '역사적 트라우마에 맞서고 인간 삶의 연약함을 드러낸 강렬한 시적 산문'으로 노벨상 수상.", "historical_significance": "한국 문학의 찬란한 세계적 공인이자 아시아 여성 작가 최초의 노벨문학상."},
    {"id": "art-084-squid-game-global-number-one", "title": "황동혁 감독의 넷플릭스 드라마 『오징어 게임』 전 세계 1위 (2021년)", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2021, "year_end": 2022, "summary": "456억 원의 상금을 건 목숨을 건 어린이 놀이 서바이벌을 통해 글로벌 자본주의 경쟁 사회를 날카롭게 풍자(에미상 6관왕).", "historical_significance": "넷플릭스 역사상 최다 시청 시간을 기록한 글로벌 K-콘텐츠의 대도약."},
    {"id": "art-085-phantom-of-the-opera-musical", "title": "앤드루 로이드 웨버의 뮤지컬 『오페라의 유령(The Phantom of the Opera)』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1986, "year_end": 1988, "summary": "파리 오페라 하우스의 샹들리에 추락과 팬텀의 비극적 사랑을 웅장한 오케스트라 넘버(Think of Me, Music of the Night)로 무대화.", "historical_significance": "브로드웨이 최장기 공연 기록을 세운 웨스트엔드·브로드웨이 뮤지컬의 대명사."},
    {"id": "art-086-frida-kahlo-self-portraits", "title": "프리다 칼로의 초현실주의적 자화상과 멕시코 민중 미술", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1938, "year_end": 1954, "summary": "교통사고의 육체적 고통과 디에고 리베라와의 격정적 사랑을 멕시코 전통 색채와 가시밭길 자화상으로 표현.", "historical_significance": "20세기 페미니즘 미술과 자전적 회화의 불멸의 상징."},
    {"id": "art-087-frank-lloyd-wright-fallingwater", "title": "프랭크 로이드 라이트의 낙수재(Fallingwater) 유기적 건축", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1935, "year_end": 1939, "summary": "폭포 위에 캔틸레버(돌출 발코니) 콘크리트 슬래브를 얹어 자연 암반과 폭포 소리가 집 안으로 녹아들게 한 유기적 건축.", "historical_significance": "현대 유기적 건축(Organic Architecture)의 최고 걸작(유네스코 세계유산)."},
    {"id": "art-088-sydney-opera-house-utzon", "title": "요른 웃손의 시드니 오페라 하우스 완공 (20세기 조각 건축의 정점)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1959, "year_end": 1973, "summary": "항구 바다 위에 조개껍데기와 돛을 형상화한 구형(Spherical) 프리캐스트 콘크리트 지붕을 얹은 혁신적 건축.", "historical_significance": "20세기 인류 건축 공학의 기적적 랜드마크."},
    {"id": "art-089-cinematographe-lumiere-brothers", "title": "뤼미에르 형제의 시네마토그래프 발명과 최초의 영화 상영 (1895년)", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1895, "year_end": 1895, "summary": "파리 그랑 카페에서 스크린에 영사한 『열차의 도착』, 『공장을 나서는 노동자들』 유료 상영 성공.", "historical_significance": "20세기 제7의 예술 '영화(Cinema)'의 공식 탄생."},
    {"id": "art-090-louis-armstrong-jazz-improvisation", "title": "루이 암스트롱의 트럼펫 솔로와 재즈 즉흥 연주(Improvisation) 혁명", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1925, "year_end": 1928, "summary": "뉴올리언스 핫 파이브/핫 세븐 레코딩을 통해 집단 연주에서 독주 솔리스트와 스캣(Scat) 보컬 중심의 재즈로 전환.", "historical_significance": "20세기 미국 대중음악과 재즈의 대부."},
    {"id": "art-091-bob-dylan-poetic-folk-nobel", "title": "밥 딜런의 포크 음악 혁명과 노벨문학상 수상", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1963, "year_end": 2016, "summary": "『Blowin' in the Wind』, 『Like a Rolling Stone』을 통해 반전 평화와 저항의 시적 가사를 대중음악에 도입(2016 노벨문학상).", "historical_significance": "대중가요 가사를 위대한 문학의 반열에 올린 음악 혁신."},
    {"id": "art-092-jean-michel-basquiat-graffiti", "title": "장 미셸 바스키아의 낙서화(신표현주의)와 거리 예술", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1980, "year_end": 1988, "summary": "뉴욕 지하철 그라피티(SAMO)에서 출발하여 왕관, 해골, 아프리카 디아스포라의 텍스트와 원시적 에너지를 캔버스에 폭발시킴.", "historical_significance": "거리 미술을 현대 파인 아트의 중심에 세운 20세기 천재 화가."},
    {"id": "art-093-banksy-street-art-shredder", "title": "뱅크시의 게릴라 스트리트 아트와 파격적 미술관 경매 퍼포먼스", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "B", "year_start": 2000, "year_end": 2018, "summary": "얼굴 없는 그래피티 아티스트로 반전, 반자본주의 메시지를 스텐실 벽화로 남기고, 경매 낙찰 순간 작품(『풍선과 소녀』)을 파쇄기로 분쇄.", "historical_significance": "미술 시장 자본화와 제도권 권위를 통렬히 조롱한 21세기 예술 혁신."},
    {"id": "art-094-hayao-miyazaki-studio-ghibli-magic", "title": "스튜디오 지브리의 서정적 판타지 명작 (『이웃집 토토로』, 『원령공주』)", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "B", "year_start": 1988, "year_end": 1997, "summary": "히사이시 조의 서정적인 음악과 자연과의 공존, 반전을 주제로 한 장인 정신의 핸드드로잉 애니메이션 세계 구축.", "historical_significance": "세계 애니메이션 영화의 서정적 지평을 넓힌 거장."},
    {"id": "art-095-cirque-du-soleil-art-circus", "title": "태양의 서커스(Cirque du Soleil)의 서사 아트 서커스 혁명", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "C", "year_start": 1984, "year_end": 2000, "summary": "동물 쇼를 배제하고 음악, 조명, 무용, 철학적 서사와 초인적 곡예를 결합한 라스베이거스 『O』, 『KA』 공연.", "historical_significance": "사양길의 서커스를 블루오션 최고급 공연 예술로 부활."},
    {"id": "art-096-korean-webtoon-global-revolution", "title": "한국 웹툰(Webtoon)의 세로 스크롤 디지털 만화 혁명", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "B", "year_start": 2003, "year_end": 2026, "summary": "스마트폰 화면에 최적화된 세로 스크롤 연출과 풀컬러 디지털 만화 포맷을 창안하여 전 세계 글로벌 만화 시장 석권 및 영상화(IP) 열풍.", "historical_significance": "디지털 시대의 새로운 글로벌 시각 스토리텔링 표준 확립."},
    {"id": "art-097-yayoi-kusama-infinity-mirrors", "title": "쿠사마 야요이의 물방울무늬(Polka Dots)와 『무한 거울의 방』", "region_id": "CHINA", "category_id": "ART_CULTURE", "importance": "C", "year_start": 1965, "year_end": 2020, "summary": "자신의 환각 증세를 호박 조각과 무한히 반사되는 거울 방의 반복적인 땡땡이 점들로 승화시킨 전위 예술.", "historical_significance": "현대 설치 미술과 관객 몰입형 전시의 최고 인기 작가."},
    {"id": "art-098-damien-hirst-shark-installation", "title": "데미안 허스트의 『살아있는 자의 마음속에 있는 죽음의 육체적 불가능성』", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "C", "year_start": 1991, "year_end": 1991, "summary": "포름알데히드 유리 수조 속에 4m짜리 타이거 상어를 통째로 박제하여 전시(yBa 운동의 대표작).", "historical_significance": "죽음과 삶의 충격적 시각화를 통해 현대 미술계를 뒤흔든 화제작."},
    {"id": "art-099-bts-love-yourself-world-tour", "title": "방탄소년단(BTS)의 웸블리 스타디움 공연과 LOVE YOURSELF 글로벌 메시지", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "A", "year_start": 2018, "year_end": 2019, "summary": "영국 팝의 성지 웸블리 스타디움을 비영어권 가수 최초로 매진시키고 전 세계 청년들에게 '자신을 사랑하라'는 연대 선언.", "historical_significance": "음악을 통한 전 지구적 팬덤(ARMY) 문화와 긍정적 사회 변혁 운동."},
    {"id": "art-100-korean-food-k-wave-global", "title": "K-푸드(김치·비빔밥·K-치킨·불닭)의 글로벌 문화 유행", "region_id": "KOREA", "category_id": "ART_CULTURE", "importance": "B", "year_start": 2010, "year_end": 2026, "summary": "발효 과학 김치(유네스코 인류무형문화유산 김장문화)와 한국 길거리 음식, K-바비큐가 전 세계 미식 트렌드로 정착.", "historical_significance": "한국 고유의 식문화가 글로벌 라이프스타일로 확고히 자리잡음."}
]

def export_art_100():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_path = os.path.join(base_dir, "data", "themes", "art_culture_100.json")
    
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump({
            "theme": "ART_CULTURE",
            "title": "역사상 가장 위대한 예술·음악·미술·문학 마일스톤 100선 (Ancient to Modern)",
            "count": len(ART_100),
            "events": ART_100
        }, f, ensure_ascii=False, indent=2)
        
    print(f"✅ Generated {len(ART_100)} Art & Culture events -> {target_path}")

if __name__ == "__main__":
    export_art_100()
