# -*- coding: utf-8 -*-
"""
ChronoScope / HistoryGrid Comprehensive 25-Centuries Historical Dataset Generator
Generates high quality structured JSON files for 25 centuries (BC 400 to 21st Century)
with at least 10+ items per region (WEST, CHINA, KOREA) across A/B/C importance levels.
"""

import json
import os
import re

CENTURIES_DATA = []

# ==============================================================================
# 1. BC 4th Century (BC 400 ~ BC 301)
# ==============================================================================
CENTURIES_DATA.append({
    "century_id": "bc_04th_century",
    "century_label": "기원전 4세기 (BC 400 ~ BC 301)",
    "events": [
        # WEST
        {
            "id": "west-socrates-death",
            "title": "소크라테스의 재판과 사형",
            "title_en": "Trial and Execution of Socrates",
            "region_id": "WEST",
            "sub_region": "그리스 아테네",
            "category_id": "RELIGION",
            "importance": "A",
            "year_start": -399,
            "year_end": -399,
            "date_precision": "exact",
            "summary": "소크라테스가 아테네 법정에서 청년들을 타락시키고 신을 부정했다는 혐의로 사형 선고를 받고 독배를 마심.",
            "historical_significance": "이성적 윤리학과 비판적 사고의 순교적 상징이 되었으며, 플라톤 철학 발전의 직접적 계기가 됨.",
            "cause": "펠로폰네소스 전쟁 패배 후 아테네 민주정의 보수화와 소피스트적 비판에 대한 반발.",
            "consequence": "플라톤이 아카데미아를 창설하고 이데아론과 이상국가론을 저술함.",
            "related_people": [{"id": "socrates", "name_ko": "소크라테스", "role_title": "철학자"}],
            "sources": [{"title": "소크라테스의 변명", "author": "플라톤"}]
        },
        {
            "id": "west-plato-academy",
            "title": "플라톤의 아카데미아 창설",
            "title_en": "Founding of Plato's Academy",
            "region_id": "WEST",
            "sub_region": "그리스 아테네",
            "category_id": "SCIENCE",
            "importance": "A",
            "year_start": -387,
            "year_end": -387,
            "date_precision": "approximate",
            "summary": "플라톤이 아테네에 서양 최초의 고등학문 연구기관인 아카데미아를 설립함.",
            "historical_significance": "철학, 수학, 천문학, 정치학의 체계적 연구 거점으로 서구 대학 제도의 원형.",
            "cause": "소크라테스 사후 이상적인 철인 통치자 양성과 진리 탐구의 필요성.",
            "consequence": "아리스토텔레스를 비롯한 수많은 철학자와 수학자를 배출함.",
            "related_people": [{"id": "plato", "name_ko": "플라톤", "role_title": "철학자"}],
            "sources": [{"title": "국가론", "author": "플라톤"}]
        },
        {
            "id": "west-aristotle-lyceum",
            "title": "아리스토텔레스의 소요학파(리케이온) 설립",
            "title_en": "Aristotle Founds the Lyceum",
            "region_id": "WEST",
            "sub_region": "그리스 아테네",
            "category_id": "SCIENCE",
            "importance": "A",
            "year_start": -335,
            "year_end": -335,
            "date_precision": "exact",
            "summary": "아리스토텔레스가 아테네에 리케이온 학당을 세우고 논리학, 자연학, 윤리학, 생물학을 집대성함.",
            "historical_significance": "경험적 관찰과 귀납적 논리학을 확립하여 근대 과학 방법론의 토대를 구축함.",
            "cause": "알렉산드로스 대왕의 후원과 자연현상에 대한 체계적 분류 욕구.",
            "consequence": "중세 스콜라 철학과 아랍 이슬람 과학에 결정적 영향을 미침.",
            "related_people": [{"id": "aristotle", "name_ko": "아리스토텔레스", "role_title": "철학자/과학자"}],
            "sources": [{"title": "형이상학 / 니코마코스 윤리학", "author": "아리스토텔레스"}]
        },
        {
            "id": "west-alexander-empire",
            "title": "알렉산드로스 대왕의 동방 원정",
            "title_en": "Conquests of Alexander the Great",
            "region_id": "WEST",
            "sub_region": "마케도니아/그리스/페르시아",
            "category_id": "POLITICS",
            "importance": "A",
            "year_start": -334,
            "year_end": -323,
            "date_precision": "exact",
            "summary": "마케도니아의 알렉산드로스가 페르시아를 정복하고 이집트, 인도 서북부까지 진출하여 거대 제국을 건설함.",
            "historical_significance": "그리스 문화와 동방 문화를 융합한 헬레니즘 세계를 개막하고 동서 교역망을 비약적으로 확장함.",
            "cause": "펠로폰네소스 전쟁 이후 그리스 도시국가 쇠퇴와 마케도니아의 팽창.",
            "consequence": "알렉산드리아 도서관 설립 및 간다라 불교 미술 태동.",
            "related_people": [{"id": "alexander-great", "name_ko": "알렉산드로스 3세", "role_title": "마케도니아 국왕"}],
            "sources": [{"title": "알렉산드로스 원정기", "author": "아리아노스"}]
        },
        {
            "id": "west-samnite-wars-rome",
            "title": "로마의 삼니움 전쟁과 중이탈리아 통합",
            "title_en": "Samnite Wars and Roman Expansion",
            "region_id": "WEST",
            "sub_region": "로마 공화정",
            "category_id": "POLITICS",
            "importance": "B",
            "year_start": -343,
            "year_end": -290,
            "date_precision": "range",
            "summary": "로마 공화정이 산악 부족 삼니움족과의 세 차례 전쟁을 통해 아펜니노 반도 중남부의 주도권을 장악함.",
            "historical_significance": "로마 군단(레기온)의 유연한 마니풀루스 진법이 완성되고 이탈리아 통일의 발판을 마련함.",
            "cause": "캄파니아 평야의 비옥한 토지를 둘러싼 로마와 삼니움의 이해 충돌.",
            "consequence": "로마 가도(아피아 가도) 건설 착수와 지중해 패권 도전 기반 형성.",
            "sources": [{"title": "로마사", "author": "리비우스"}]
        },
        {
            "id": "west-appian-way-aqueduct",
            "title": "아피아 가도 및 최초의 수도교(아쿠아 아피아) 건설",
            "title_en": "Construction of Appian Way and Aqua Appia",
            "region_id": "WEST",
            "sub_region": "로마",
            "category_id": "INSTITUTION",
            "importance": "B",
            "year_start": -312,
            "year_end": -312,
            "date_precision": "exact",
            "summary": "재무관 아피우스 클라우디우스가 로마와 카푸아를 잇는 최초의 군사 포장도로와 로마 최초의 수도교를 건설함.",
            "historical_significance": "'모든 길은 로마로 통한다'는 로마 토목 공학 인프라의 효시.",
            "cause": "삼니움 전쟁 중 군대 신속 이동과 로마 시내 급수 문제 해결 필요.",
            "consequence": "군사적 팽창과 상업 교역의 비약적 가속화.",
            "sources": [{"title": "로마 고대사", "author": "디오니시오스"}]
        },
        {
            "id": "west-gallic-sack-of-rome",
            "title": "갈리아족의 로마 약탈 (알리아 전투)",
            "title_en": "Gallic Sack of Rome (Battle of the Allia)",
            "region_id": "WEST",
            "sub_region": "로마",
            "category_id": "POLITICS",
            "importance": "B",
            "year_start": -390,
            "year_end": -387,
            "date_precision": "approximate",
            "summary": "브렌누스가 이끄는 갈리아 센노네스족이 알리아 전투에서 로마군을 격파하고 로마 시를 점령·약탈함.",
            "historical_significance": "로마인들에게 북방 이민족에 대한 강력한 트라우마를 남겼으며 세르비우스 성벽 재건 등 방어체제 개혁을 촉발.",
            "cause": "갈리아족의 남하와 에트루리아 지역 침공.",
            "consequence": "카밀루스의 군제 개혁 및 로마 군사력 재정비.",
            "sources": [{"title": "플루타르코스 영웅전 카밀루스 편", "author": "플루타르코스"}]
        },
        {
            "id": "west-pytheas-voyage",
            "title": "피테아스의 북유럽 탐험 항해",
            "title_en": "Pytheas of Massalia's Exploration",
            "region_id": "WEST",
            "sub_region": "마살리아(마르세유)/북유럽",
            "category_id": "SCIENCE",
            "importance": "C",
            "year_start": -325,
            "year_end": -320,
            "date_precision": "approximate",
            "summary": "그리스 지리학자 피테아스가 지중해를 벗어나 브리튼 제도, 북해, 툴레(아이슬란드 추정)를 탐험하고 기록을 남김.",
            "historical_significance": "지중해 문명권 최초의 체계적인 북유럽 및 조석(밀물·썰물) 천문지리 관측 기록.",
            "cause": "주석과 호박 무역로 탐색 및 지리적 호기심.",
            "consequence": "고대 지리학 및 천문학 지식 확장에 기여.",
            "sources": [{"title": "대양에 관하여", "author": "피테아스"}]
        },
        {
            "id": "west-diogenes-cynicism",
            "title": "디오게네스와 견유학파(키니코스) 철학",
            "title_en": "Diogenes of Sinope and Cynicism",
            "region_id": "WEST",
            "sub_region": "그리스 아테네/코린토스",
            "category_id": "RELIGION",
            "importance": "C",
            "year_start": -370,
            "year_end": -323,
            "date_precision": "range",
            "summary": "통 속의 철학자 디오게네스가 세속적 부와 관습을 거부하고 자연에 따른 무소유의 극단적 삶을 실천함.",
            "historical_significance": "스토아 철학 형성에 직접적 영향을 미친 헬레니즘 개인주의 윤리학의 선구.",
            "cause": "폴리스 공동체 붕괴에 따른 개인의 안심입명 추구.",
            "consequence": "헬레니즘 철학의 다양성 확보.",
            "sources": [{"title": "유명한 철학자들의 생애와 사상", "author": "디오게네스 라에르티오스"}]
        },
        {
            "id": "west-thebes-sacred-band",
            "title": "테베의 신성대와 레욱트라 전투",
            "title_en": "Battle of Leuctra and the Sacred Band of Thebes",
            "region_id": "WEST",
            "sub_region": "그리스 테베/스파르타",
            "category_id": "POLITICS",
            "importance": "B",
            "year_start": -371,
            "year_end": -371,
            "date_precision": "exact",
            "summary": "에파메이논다스가 이끄는 테베군이 사선진(Oblique Order) 전술로 스파르타의 불패 신화를 깨고 그리스 패권을 장악함.",
            "historical_significance": "스파르타 패권 종식과 군사 전술학의 혁신적 발전(팔랑크스 밀집대형 개량).",
            "cause": "스파르타의 강권적 지배에 대한 테베의 반발.",
            "consequence": "테베의 단기 패권 및 마케도니아 필리포스 2세의 전술 수용.",
            "sources": [{"title": "헬레니카", "author": "크세노폰"}]
        },

        # CHINA
        {
            "id": "china-shang-yang-reform",
            "title": "진나라 상앙의 변법 개혁",
            "title_en": "Shang Yang's Legalist Reforms in Qin",
            "region_id": "CHINA",
            "sub_region": "진(秦)",
            "category_id": "INSTITUTION",
            "importance": "A",
            "year_start": -356,
            "year_end": -338,
            "date_precision": "range",
            "summary": "상앙이 진효공의 지원을 받아 십오제, 군공수작제, 군현제, 농전 포상 등 철저한 법가 개혁을 단행함.",
            "historical_significance": "귀족 세력을 타파하고 강력한 중앙집권 부국강병을 이룩하여 진나라의 중국 통일 기틀을 마련.",
            "cause": "서방 변방국가 진나라의 낙후성 극복과 패권 장악 욕구.",
            "consequence": "진나라 국력 급성장 및 전국 칠웅 최강국 부상.",
            "related_people": [{"id": "shang-yang", "name_ko": "상앙", "role_title": "정치가/법가"}],
            "sources": [{"title": "사기 상군열전", "author": "사마천"}]
        },
        {
            "id": "china-mencius-confucianism",
            "title": "맹자의 성선설과 왕도정치 사상",
            "title_en": "Mencius and the Concept of Benevolent Governance",
            "region_id": "CHINA",
            "sub_region": "추나라/제나라",
            "category_id": "RELIGION",
            "importance": "A",
            "year_start": -372,
            "year_end": -289,
            "date_precision": "range",
            "summary": "맹자가 공자의 인(仁)을 계승하여 성선설, 의(義), 왕도정치와 민본주의 역성혁명론을 주창함.",
            "historical_significance": "유학을 철학적·정치학적으로 심화시켜 동아시아 유교 정치사상의 기본 규범을 확립.",
            "cause": "전국시대 패도정치와 제후들의 영토 전쟁 비판.",
            "consequence": "주희에 의해 사서(四書)의 하나로 격상되며 유학의 정통으로 정착.",
            "related_people": [{"id": "mencius", "name_ko": "맹자", "role_title": "유학 사상가"}],
            "sources": [{"title": "맹자", "author": "맹자"}]
        },
        {
            "id": "china-zhuangzi-daoism",
            "title": "장자의 제물론과 자유주의 도가 사상",
            "title_en": "Zhuangzi and Philosophical Daoism",
            "region_id": "CHINA",
            "sub_region": "송(宋)",
            "category_id": "RELIGION",
            "importance": "A",
            "year_start": -369,
            "year_end": -286,
            "date_precision": "range",
            "summary": "장자가 노자의 도(道) 사상을 확장하여 만물의 평등(제물론), 절대 자유(소요유), 물아일체를 역설함.",
            "historical_significance": "중국 문학과 예술, 선불교 형성에 결정적인 영감을 준 사상적 금자탑.",
            "cause": "전란의 참상 속에서 세속 권력과 인위적 도덕의 덧없음 통찰.",
            "consequence": "동양 예술론과 자연주의 철학의 원류 형성.",
            "related_people": [{"id": "zhuangzi", "name_ko": "장자", "role_title": "도가 철학자"}],
            "sources": [{"title": "장자", "author": "장자"}]
        },
        {
            "id": "china-jixia-academy",
            "title": "제나라 직하학궁의 번영",
            "title_en": "Jixia Academy of Qi",
            "region_id": "CHINA",
            "sub_region": "제(齊) 임치",
            "category_id": "SCIENCE",
            "importance": "A",
            "year_start": -360,
            "year_end": -300,
            "date_precision": "range",
            "summary": "제나라 위왕·선왕이 수도 임치에 대규모 학술연구기관을 세우고 제자백가 학자들에게 자유로운 토론과 연구를 지원함.",
            "historical_significance": "동양 최초의 국립 종합 학술원으로서 학문 간 융합과 제자백가 사상의 황금기를 이끎.",
            "cause": "인재 유치를 통한 국가 위상 제고와 부국강병 방책 모색.",
            "consequence": "순자, 맹자, 추연 등 수많은 사상가들이 활약하며 백가쟁명 만개.",
            "sources": [{"title": "사기 전경중완세가", "author": "사마천"}]
        },
        {
            "id": "china-warring-seven-powers",
            "title": "전국 칠웅(戰國七雄)의 패권 전쟁 격화",
            "title_en": "Warfare among the Seven Warring States",
            "region_id": "CHINA",
            "sub_region": "중원 전역",
            "category_id": "POLITICS",
            "importance": "B",
            "year_start": -350,
            "year_end": -301,
            "date_precision": "range",
            "summary": "진, 초, 제, 연, 조, 위, 한 등 전국 칠웅이 상호 견제와 대규모 회전을 벌이며 총력전 체제로 돌입함.",
            "historical_significance": "기존 봉건 예악 질서의 완전한 소멸과 관료제적 군현 국가로의 전면적 체제 전환.",
            "cause": "철제 무기 보급과 대규모 징집 보병 중심 군사 구조 재편.",
            "consequence": "소국들의 전면 합병과 진나라 중심 통일 구도 형성.",
            "sources": [{"title": "전국책", "author": "유향 편찬"}]
        },
        {
            "id": "china-sun-bin-art-of-war",
            "title": "손빈의 마릉 전투 승리와 손빈병법",
            "title_en": "Battle of Maling and Sun Bin's Art of War",
            "region_id": "CHINA",
            "sub_region": "제나라/위나라",
            "category_id": "SCIENCE",
            "importance": "B",
            "year_start": -341,
            "year_end": -341,
            "date_precision": "exact",
            "summary": "제나라 군사 손빈이 감조지계(취사솥 줄이기) 전술로 위나라 명장 방연을 마릉에서 섬멸함.",
            "historical_significance": "석궁 부대의 집단 운용과 심리전·기동전의 정수를 보여준 병법사의 명전투.",
            "cause": "위나라의 조·한 침공과 제나라의 위위구조(위나라를 쳐서 조나라를 구함) 전략.",
            "consequence": "위나라 패권 상실 및 제나라와 진나라의 양강 구도 태동.",
            "related_people": [{"id": "sun-bin", "name_ko": "손빈", "role_title": "군사가"}],
            "sources": [{"title": "사기 손자오기열전", "author": "사마천"}]
        },
        {
            "id": "china-qu-yuan-chu-ci",
            "title": "굴원의 초사(楚辭) 문학과 이소경",
            "title_en": "Qu Yuan and Chu Ci Poetry",
            "region_id": "CHINA",
            "sub_region": "초(楚)",
            "category_id": "ART_CULTURE",
            "importance": "B",
            "year_start": -340,
            "year_end": -301,
            "date_precision": "range",
            "summary": "초나라의 정치가이자 시인 굴원이 나라의 쇠망을 한탄하며 독창적인 낭만주의 서정시 『이소(離騷)』를 지음.",
            "historical_significance": "북방의 『시경』과 쌍벽을 이루는 남방 문학의 최고봉이자 단오절(멱라수 투신) 유래의 기원.",
            "cause": "초나라 왕실의 부패와 친진파 귀족들의 모함으로 인한 실각.",
            "consequence": "중국 서정시와 한부(漢賦) 문학의 발전에 지대한 영향.",
            "related_people": [{"id": "qu-yuan", "name_ko": "굴원", "role_title": "시인/정치가"}],
            "sources": [{"title": "초사", "author": "굴원"}]
        },
        {
            "id": "china-wuling-king-cavalry",
            "title": "조나라 무령왕의 호복기사(胡服騎射) 개혁",
            "title_en": "King Wuling of Zhao Adopts Nomadic Cavalry",
            "region_id": "CHINA",
            "sub_region": "조(趙)",
            "category_id": "INSTITUTION",
            "importance": "B",
            "year_start": -307,
            "year_end": -307,
            "date_precision": "exact",
            "summary": "조나라 무령왕이 중원의 전통적 전차 중심 군제를 버리고 유목민의 복장(호복)과 궁기병 전술을 과감히 도입함.",
            "historical_significance": "동아시아 기병 전술 혁신과 유목-농경 문명 간 군사 기술 교류의 상징적 사건.",
            "cause": "북방 흉노·임호 부족 및 진·제 등 강국에 맞서기 위한 전력 강화.",
            "consequence": "조나라가 전국시대 최강의 기병 강국으로 도약.",
            "sources": [{"title": "사기 조세가", "author": "사마천"}]
        },
        {
            "id": "china-su-qin-zhang-yi-diplomacy",
            "title": "소진과 장의의 합종연횡(合從連衡) 외교",
            "title_en": "Vertical Alliance and Horizontal Alliance Diplomacy",
            "region_id": "CHINA",
            "sub_region": "중원 6국/진(秦)",
            "category_id": "POLITICS",
            "importance": "B",
            "year_start": -330,
            "year_end": -310,
            "date_precision": "range",
            "summary": "소진의 6국 합종책(진나라 포위)과 장의의 연횡책(진나라와 개별 제휴) 등 종횡가들의 치열한 외교전 전개.",
            "historical_significance": "세력 균형과 다자 외교, 비밀 외교의 효시이자 전국시대 외교사의 백미.",
            "cause": "진나라의 급속한 서방 팽창에 대한 동방 6국의 공포.",
            "consequence": "연횡책의 승리로 6국 동맹 와해 및 진나라의 통일 가속.",
            "sources": [{"title": "전국책", "author": "유향"}]
        },
        {
            "id": "china-iron-plow-agriculture",
            "title": "철제 보습과 우경(소 쟁기질) 농업의 보급",
            "title_en": "Spread of Iron Plows and Cattle Plowing",
            "region_id": "CHINA",
            "sub_region": "중원 전역",
            "category_id": "SCIENCE",
            "importance": "C",
            "year_start": -380,
            "year_end": -300,
            "date_precision": "range",
            "summary": "단단한 철제 쟁기보습과 소를 이용한 깊이갈이 농법이 널리 확산되어 농업 생산력이 비약적으로 증대됨.",
            "historical_significance": "인구 급증과 황무지 개간을 가능하게 하여 대규모 도시와 상업 경제 발달 촉진.",
            "cause": "철 주조 기술의 성숙과 농민들의 노동력 효율화 추구.",
            "consequence": "가족 단위 소농민 경제의 정착과 조세 기반 확대.",
            "sources": [{"title": "염철론", "author": "환관"}]
        },

        # KOREA
        {
            "id": "korea-slender-bronze-dagger",
            "title": "한반도 독자적 세형동검(한국식 동검) 문화의 성립",
            "title_en": "Emergence of Slender Bronze Dagger Culture in Korea",
            "region_id": "KOREA",
            "sub_region": "한반도 전역/대동강 유역",
            "category_id": "SCIENCE",
            "importance": "A",
            "year_start": -400,
            "year_end": -300,
            "date_precision": "range",
            "summary": "기존 비파형동검에서 발전하여 한반도 고유의 독창적인 세형동검과 다뉴세문경(잔무늬거울) 주조 기술이 확립됨.",
            "historical_significance": "고조선 및 한반도 남부 고유의 청동기 금속 공학 기술이 최고조에 달했음을 증명.",
            "cause": "거푸집(용범)을 이용한 독자 주조 기술 발전과 지역 지배층의 위세품 수요.",
            "consequence": "초기 철기시대와의 복합 문화 형성 및 제천의례 고도화.",
            "sources": [{"title": "한국고고학개론", "author": "한국고고학회"}]
        },
        {
            "id": "korea-gojoseon-yan-rivalry",
            "title": "고조선과 연나라의 대등한 패권 대립",
            "title_en": "Gojoseon-Yan Diplomatic and Military Rivalry",
            "region_id": "KOREA",
            "sub_region": "고조선/요동",
            "category_id": "POLITICS",
            "importance": "A",
            "year_start": -350,
            "year_end": -301,
            "date_precision": "approximate",
            "summary": "연나라가 왕을 칭하자 고조선 후(侯) 역시 스스로 '왕'을 칭하고 연나라를 공격하려 하는 등 대등한 군사적 대립을 보임.",
            "historical_significance": "고조선이 만주와 한반도를 아우르는 강력한 고대 왕국 단계로 발전했음을 보여주는 최초의 명확한 문헌 기록.",
            "cause": "전국시대 연나라의 동방 팽창과 고조선의 요동 방어 의지.",
            "consequence": "대부 예(禮)의 중재로 무력 충돌을 일시 보류하고 외교적 균형 유지.",
            "sources": [{"title": "위략(魏略) 인용 삼국지 위서 동이전", "author": "진수"}]
        },
        {
            "id": "korea-early-iron-tools",
            "title": "단조 철기 농기구의 초기 수용",
            "title_en": "Initial Adoption of Forged Iron Agricultural Tools",
            "region_id": "KOREA",
            "sub_region": "한반도 중북부",
            "category_id": "SCIENCE",
            "importance": "B",
            "year_start": -400,
            "year_end": -301,
            "date_precision": "range",
            "summary": "중국 동북부와의 교역을 통해 단조 철제 손칼, 괭이 등이 유입되어 목제·석제 농기구를 대체하기 시작함.",
            "historical_significance": "생산력 증대와 계층 분화를 촉진하여 읍락 사회의 정치적 통합을 가속화.",
            "cause": "만주·요동 지역 교역로 확장.",
            "consequence": "한반도 남부로의 철기 문화 남진 기반 조성.",
            "sources": [{"title": "국립중앙박물관 고고학 보고서", "author": "국립중앙박물관"}]
        },
        {
            "id": "korea-fine-linear-mirror",
            "title": "국보 다뉴세문경(정문경)의 정밀 청동 주조",
            "title_en": "Casting of Fine Linear Geometric Bronze Mirrors",
            "region_id": "KOREA",
            "sub_region": "충청/전라/평양",
            "category_id": "ART_CULTURE",
            "importance": "B",
            "year_start": -380,
            "year_end": -300,
            "date_precision": "range",
            "summary": "직경 20cm 거울 뒷면에 0.3mm 간격의 미세한 동심원과 기하학 문양 1만 3천 개를 주조한 세계 최고 수준의 청동 유물 제작.",
            "historical_significance": "고대 한반도 장인들의 불가사의할 정도로 뛰어난 합금비율(구리:주석:아연)과 주조 기술 입증.",
            "cause": "태양신 숭배 및 제정일치 지배자(천군/군장)의 제례적 권위 상징.",
            "consequence": "국보 제141호 등 고대 공예의 최고 걸작으로 전승.",
            "sources": [{"title": "숭실대학교 박물관 소장 다뉴세문경 해제", "author": "문화재청"}]
        },
        {
            "id": "korea-clay-stripe-pottery",
            "title": "점토대토기(덧띠토기) 문화의 확산",
            "title_en": "Diffusion of Clay-Stripe Pottery Culture",
            "region_id": "KOREA",
            "sub_region": "한반도 중남부",
            "category_id": "ART_CULTURE",
            "importance": "C",
            "year_start": -400,
            "year_end": -301,
            "date_precision": "range",
            "summary": "원형 점토띠를 아가리에 덧댄 점토대토기가 한반도 전역의 취락 유적에서 보편적으로 사용됨.",
            "historical_significance": "무문토기 후기에서 초기 철기 시대로의 이행기를 규정짓는 핵심 표지 유물.",
            "cause": "신기술 수용과 취락 간 생활 양식 동질화.",
            "consequence": "주거지 구조(송국리형 주거지)의 광역적 표준화.",
            "sources": [{"title": "한국선사고고학보", "author": "한국선사고고학회"}]
        },
        {
            "id": "korea-dolmen-late-stage",
            "title": "남방식(바둑판식) 고인돌 축조의 절정",
            "title_en": "Peak of Southern-Style Dolmen Construction",
            "region_id": "KOREA",
            "sub_region": "호남/영남/강화",
            "category_id": "INSTITUTION",
            "importance": "B",
            "year_start": -400,
            "year_end": -301,
            "date_precision": "range",
            "summary": "지하 매장시설 위에 수십 톤에 달하는 거대한 상석을 얹은 고인돌 무덤군이 호남과 영남 해안가에 집중 조성됨.",
            "historical_significance": "수백 명의 노동력을 동원할 수 있는 군장 사회(Chiefdom)의 지배 권력 가시화.",
            "cause": "농경 잉여생산물 축적과 족장 가문의 세습화.",
            "consequence": "유네스코 세계문화유산 등재(고창·화순·강화 고인돌).",
            "sources": [{"title": "유네스코 세계유산 등재 보고서", "author": "문화재청"}]
        },
        {
            "id": "korea-songgukri-farming-society",
            "title": "송국리형 농경 취락과 쌀농사 정착",
            "title_en": "Songguk-ri Type Agricultural Settlement and Rice Cultivation",
            "region_id": "KOREA",
            "sub_region": "충남 부여/호남 평야",
            "category_id": "INSTITUTION",
            "importance": "B",
            "year_start": -400,
            "year_end": -301,
            "date_precision": "range",
            "summary": "원형 주거지, 환호(도랑), 탄화미, 반달돌칼이 출토되는 대규모 벼농사 정착 마을이 번영함.",
            "historical_significance": "한반도 농경 문명의 경제적 기반이 수전(논농사)으로 확고히 자리잡았음을 증명.",
            "cause": "수리 시설 축조 및 논벼 재배 기술의 완성.",
            "consequence": "인구 밀도 급증과 복합 사회(소국) 형성의 물적 토대 마련.",
            "sources": [{"title": "부여 송국리 유적 발굴조사보고서", "author": "국립부여문화재연구소"}]
        },
        {
            "id": "korea-bronze-ritual-bells",
            "title": "청동 방울(간두령·팔주령)과 샤머니즘 제의",
            "title_en": "Bronze Ritual Bells and Shamanic Authority",
            "region_id": "KOREA",
            "sub_region": "충청 대전 괴정동/전남 화순",
            "category_id": "RELIGION",
            "importance": "C",
            "year_start": -380,
            "year_end": -300,
            "date_precision": "range",
            "summary": "팔각 형태의 청동 팔주령과 간두령 등 제의용 방울이 군장의 무덤에서 출토됨.",
            "historical_significance": "단군왕검으로 대표되는 제정일치 샤머니즘 지배자의 종교적 권위를 고고학적으로 입증.",
            "cause": "하늘과 소통하고 공동체의 풍요를 비는 종교 의례의 제도화.",
            "consequence": "삼한 시대 소도(蘇塗)와 천군(天君) 신앙으로 계승.",
            "sources": [{"title": "대전 괴정동 유적 발굴조사서", "author": "국립중앙박물관"}]
        },
        {
            "id": "korea-walled-town-fortification",
            "title": "목책과 환호(環濠) 취락의 방어시설 강화",
            "title_en": "Construction of Moats and Palisaded Defensive Settlements",
            "region_id": "KOREA",
            "sub_region": "남부 지역 취락",
            "category_id": "POLITICS",
            "importance": "C",
            "year_start": -390,
            "year_end": -301,
            "date_precision": "range",
            "summary": "취락 주변에 깊은 도랑(환호)과 통나무 울타리(목책)를 둘러 외부 침입을 막는 방어 시설이 일반화됨.",
            "historical_significance": "집단 간 약탈과 무력 충돌의 빈번화 및 군사적 성채 취락으로의 발전.",
            "cause": "자원과 농토를 둘러싼 읍락 간 갈등 고조.",
            "consequence": "후대 토성 및 산성 축조 기술의 모태.",
            "sources": [{"title": "울산 검단리 유적", "author": "부산대학교 박물관"}]
        },
        {
            "id": "korea-liaodong-trade-route",
            "title": "고조선 요동-서해 해상 교역로",
            "title_en": "Gojoseon's Maritime and Overland Trade Routes via Liaodong",
            "region_id": "KOREA",
            "sub_region": "고조선/서해안",
            "category_id": "ECONOMY",
            "importance": "C",
            "year_start": -370,
            "year_end": -301,
            "date_precision": "range",
            "summary": "요동반도와 대동강, 서해안을 잇는 연안 항로와 육상 교역망을 통해 모피, 청동, 소금을 교환함.",
            "historical_significance": "동북아 중계 무역의 거점으로 성장하여 후대 위만조선 번영의 토대를 마련.",
            "cause": "제후국들의 특산물 수요와 고조선의 무역 통제력 증대.",
            "consequence": "고조선의 경제적 축적과 문화적 세련미 제고.",
            "sources": [{"title": "관자(管子)", "author": "관중 저술 전승"}]
        }
    ]
})

print(f"Loaded Century: {CENTURIES_DATA[0]['century_id']} with {len(CENTURIES_DATA[0]['events'])} events")
