# -*- coding: utf-8 -*-
"""
Generate Top 100 Landmark Philosophical & Ideological Milestones (Ancient to Modern)
Covers Western Philosophy, Eastern Thought (Confucianism, Taoism, Buddhism, Silhak), Islamic & Modern Ideologies.
"""

import json
import os

PHILOSOPHY_100 = [
    # --- Ancient Philosophy (Axial Age: 6th ~ 1st Century BC) ---
    {"id": "phi-001-thales-arche-water", "title": "탈레스의 만물 근원(아르케) '물' 선언 (서양 철학의 기원)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -585, "year_end": -585, "summary": "신화적 신들의 개입 대신 자연 현상의 근본 원리(Arche)를 자연 내부의 물질 '물'로 설명하려 시도.", "historical_significance": "밀레토스 자연철학과 서양 합리적 이성 탐구의 출발점."},
    {"id": "phi-002-upanishads-brahman-atman", "title": "인도 우파니샤드 철학의 범아일여(梵我一如) 사상", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -800, "year_end": -500, "summary": "우주의 궁극적 실재인 브라흐만(Brahman)과 개인의 참된 자아인 아트만(Atman)이 본질적으로 하나임을 설파.", "historical_significance": "힌두교 철학의 심오한 정수이자 동양 형이상학의 근간."},
    {"id": "phi-003-buddha-four-noble-truths", "title": "고타마 붓다(석가모니)의 깨달음과 사성제·연기설(緣起說)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -528, "year_end": -528, "summary": "보리수 아래에서 만물이 상호의존적으로 생겨난다는 연기법과 고·집·멸·도 4성제 및 8정도를 깨닫고 녹야원에서 초전법륜.", "historical_significance": "2,500년간 인류에게 자비와 해탈의 길을 연 세계 종교 철학의 탄생."},
    {"id": "phi-004-confucius-analects-ren-li", "title": "공자의 『논어(論語)』와 인(仁)·예(禮)·덕치주의", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -551, "year_end": -479, "summary": "사람을 사랑하는 어진 마음(仁)과 사회적 규범(禮)을 바탕으로 군자(君子)의 수양과 도덕 정치를 주창.", "historical_significance": "동아시아 2천 년 문명과 윤리 도덕의 절대적 규범 확립."},
    {"id": "phi-005-laozi-daodejing-wuwei", "title": "노자의 『도덕경(道德經)』과 무위자연(無爲自然)", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -500, "year_end": -450, "summary": "'도는 말로 표현할 수 없다(道可道非常道)'며 인위적인 조작을 버리고 자연의 순리에 따르는 무위(無爲)의 도와 상선약수(上善若水) 제시.", "historical_significance": "도가(道家) 철학의 창시이자 유교와 상보적인 동양 사상의 한 축."},
    {"id": "phi-006-heraclitus-panta-rhei-logos", "title": "헤라클레이토스의 판타 레이('만물은 유전한다')와 로고스(Logos)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -500, "year_end": -480, "summary": "'같은 강물에 두 번 발을 담글 수 없다'며 대립물의 투쟁과 끊임없는 변화 속에서 조화를 이루는 로고스 제안.", "historical_significance": "변증법적 사고의 시초이자 스토아 철학 로고스 개념의 모태."},
    {"id": "phi-007-parmenides-being-unchangeable", "title": "파르메니데스의 존재론 ('존재하는 것은 있고, 존재하지 않는 것은 없다')", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -500, "year_end": -460, "summary": "감각적 경험의 변화는 환상이며, 순수 이성으로 파악되는 진정한 '존재'는 영원불변하고 유일하다는 존재론 정립.", "historical_significance": "서양 형이상학(존재론)의 창시자."},
    {"id": "phi-008-socrates-know-thyself-midwife", "title": "소크라테스의 산파술과 '너 자신을 알라' (무지의 지)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -430, "year_end": -399, "summary": "문답법을 통해 자신이 안다고 착각하는 무지를 자각(무지의 지)하게 하고, '성찰하지 않는 삶은 살 가치가 없다'며 독배를 마심.", "historical_significance": "서양 윤리학과 철학적 대화법의 영원한 스승."},
    {"id": "phi-009-plato-theory-of-forms-republic", "title": "플라톤의 이데아론(Theory of Forms)과 이상국가론(『국가』)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -380, "year_end": -375, "summary": "동굴의 비유를 통해 감각 너머의 완전한 영원불변의 원형 '이데아'를 역설하고 철인 통치자가 다스리는 정의로운 이상 국가 제안.", "historical_significance": "'서양 철학사는 플라톤의 각주에 불과하다'는 찬사를 받은 서양 합리주의의 거인."},
    {"id": "phi-0010-aristotle-metaphysics-nicomachean", "title": "아리스토텔레스의 질료형상설과 『니코마코스 윤리학』 (중용과 행복)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -335, "year_end": -322, "summary": "형상이 현실 세계의 질료 속에 내재한다는 현실주의와 인간 삶의 궁극 목적은 덕을 통한 행복(Eudaimonia)이자 과부족이 없는 중용(Mesotes)임을 규명.", "historical_significance": "논리학, 생물학, 정치학, 윤리학을 아우른 만학의 아버지."},
    {"id": "phi-011-mencius-human-goodness-mandate", "title": "맹자의 성선설(性善說)과 사단(四端) 및 역성혁명론", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -320, "year_end": -300, "summary": "인간 본성에 측은지심 등 4단이 내재해 선하다는 성선설과 백성을 도탄에 빠뜨린 군주는 천명을 잃어 교체할 수 있다는 역성혁명 주창.", "historical_significance": "유가 도덕 철학과 민본주의 정치학의 확립자."},
    {"id": "phi-012-zhuangzi-relativism-butterfly", "title": "장자의 『장자(莊子)』와 제물론(齊物論)·호접지몽(胡蝶之夢)", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -320, "year_end": -286, "summary": "내가 나비가 된 꿈인가 나비가 내가 된 꿈인가라는 상대주의적 사유와 세속적 시비와 분별을 잊는 소요유(逍遙遊) 설파.", "historical_significance": "동양 자유주의와 심미적 예술 철학의 최고봉."},
    {"id": "phi-013-xunzi-human-nature-bad", "title": "순자의 성악설(性惡說)과 예(禮)를 통한 후천적 교화", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -280, "year_end": -238, "summary": "인간의 타고난 본성은 이기적 욕망으로 가득 차 악하므로(性惡), 스승과 법도, 예(禮)를 통한 후천적 인위적 교화(僞)가 필수적이라고 주장.", "historical_significance": "현실주의 유학과 후대 법가 사상에 지대한 영향."},
    {"id": "phi-014-han-feizi-legalism-statecraft", "title": "한비자의 법가(法家) 사상과 『한비자』 (법·술·세)", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -240, "year_end": -233, "summary": "도덕 대신 엄격한 법률(法), 신하를 다스리는 은밀한 통치 기술(術), 군주의 권력과 지위(勢)를 결합한 절대 군주 통치론 완성.", "historical_significance": "진시황의 중국 최초 중앙집권 천하통일의 통치 이념."},
    {"id": "phi-015-zeno-stoicism-apatheia", "title": "제논의 스토아학파(Stoicism) 창시와 아파테이아(Apatheia)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -300, "year_end": -260, "summary": "자연의 이법(Logos)에 순응하고 정념(욕망, 공포)에 휘둘리지 않는 부동심(Apatheia)과 만인평등의 세계시민주의(Cosmopolitanism) 주창.", "historical_significance": "로마 황제 마르쿠스 아우렐리우스, 세네카 및 근대 의무론의 원천."},
    {"id": "phi-016-epicurus-ataraxia-pleasure", "title": "에피쿠로스의 쾌락주의와 아타락시아(Ataraxia)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": -306, "year_end": -270, "summary": "육체적 방탕이 아닌 정신적 평정과 고통 없는 상태(Ataraxia), 소박한 정원 공동체에서의 우정과 지적 탐구를 최고의 선으로 제시.", "historical_significance": "근대 공리주의와 계몽주의 철학의 선구."},

    # --- Classical & Medieval Philosophy (1st ~ 14th Century) ---
    {"id": "phi-017-dong-zhongshu-confucian-orthodoxy", "title": "동중서의 천인감응설(天人感應說)과 유교 국교화", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": -134, "year_end": -130, "summary": "하늘과 인간은 상호 감응한다는 음양오행설과 유학을 결합하여 한무제에게 건의해 오경박사를 두고 유교를 제국의 통치 이념으로 확립.", "historical_significance": "유교가 동아시아 2천 년 관학(官學)으로 자리잡은 결정적 계기."},
    {"id": "phi-018-nagarjuna-madhyamaka-sunyata", "title": "나가르주나(용수)의 중관사상(中觀思想)과 공(空, Śūnyatā)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 150, "year_end": 200, "summary": "모든 존재는 고정된 실체가 없다는 공(空)과 집착을 떠난 팔불중도(八不中道)를 수학적 논리로 정립한 대승불교의 최고 논서 『중론』 저술.", "historical_significance": "'제2의 붓다'로 불리는 대승불교의 아버지이자 대승 8종의 종조."},
    {"id": "phi-019-plotinus-neoplatonism-the-one", "title": "플로티노스의 신플라톤주의와 '일자(The One)' 유출설", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 250, "year_end": 270, "summary": "만물은 궁극적인 초월자 '일자(To Hen)'로부터 지성(Nous)과 영혼(Psyche), 물질로 유출되며 관조를 통해 일자와 합일(황홀경)한다고 주장.", "historical_significance": "초기 기독교 교부 철학과 이슬람 신비주의(수피즘)의 모태."},
    {"id": "phi-020-augustine-city-of-god-confessions", "title": "아우구스티누스의 『고백록』과 『신국론(City of God)』 (교부 철학 완성)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 397, "year_end": 426, "summary": "플라톤 철학을 기독교 신학과 융합하여 원죄론, 은총론, 지상국과 신의 나라의 역사 섭리를 체계화.", "historical_significance": "중세 천 년 서양 기독교 신학과 역사철학의 뼈대."},
    {"id": "phi-021-wonhyo-hwajaeng-one-mind", "title": "신라 원효대사의 화쟁사상(和諍思想)과 일심(一心)·무애행", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 660, "year_end": 686, "summary": "『십문화쟁론』과 『대승기신론소』를 통해 불교 종파 간의 극심한 교리 대립을 더 높은 차원의 '일심'으로 조화·융합하고 표주박을 치며 민중 교화.", "historical_significance": "한국 불교의 독창적인 화쟁적 전통과 대승 불교 철학의 세계적 금자탑."},
    {"id": "phi-022-huineng-platform-sutra-sudden-enlightenment", "title": "혜능의 『육조단경』과 남종선(禪)의 돈오(頓悟) 사상", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": 677, "year_end": 713, "summary": "'본래 한 물건도 없다(本來無一物)'며 경전 문자나 점진적 수행에 얽매이지 않고 자신의 본성을 직관해 단번에 부처가 되는 돈오성불(頓悟成佛) 제창.", "historical_significance": "동아시아 선종(Zen) 불교를 주류로 확립시킨 일대 혁명."},
    {"id": "phi-023-al-farabi-islamic-political-philosophy", "title": "알 파라비의 이슬람 철학과 『이상도시론(The Virtuous City)』", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 900, "year_end": 950, "summary": "아리스토텔레스와 플라톤 철학을 이슬람 신학과 융합하여 철학자-예언자가 다스리는 이상 국가 모델 제시.", "historical_significance": "아리스토텔레스에 이은 '제2의 스승'으로 불리는 아랍 철학의 아버지."},
    {"id": "phi-024-anselm-ontological-argument", "title": "안셀무스의 존재론적 신 존재 증명 (『프로슬로기온』)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1077, "year_end": 1078, "summary": "'이보다 더 큰 것을 생각할 수 없는 완전한 존재'는 개념 속에만 있을 수 없고 필연적으로 현실에 실재해야 한다는 순수 연역 증명.", "historical_significance": "스콜라 철학과 서양 합리론 존재론의 가장 유명한 논증."},
    {"id": "phi-025-zhu-xi-neo-confucianism-sishu", "title": "주희(주자)의 성리학(性理學) 집대성과 사서집주(四書集註)", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": 1170, "year_end": 1200, "summary": "우주의 궁극 원리인 이(理)와 질료적 에너지인 기(氣)의 이기론(理氣論), 성즉리(性卽理), 격물치지(格物致知)를 체계화.", "historical_significance": "송·명·청과 조선 500년 국가 공인 최고 통치 이념이자 유학의 르네상스."},
    {"id": "phi-026-averroes-double-truth-aristotle", "title": "이븐 루슈드(아베로에스)의 아리스토텔레스 주해와 이성적 합리주의", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1180, "year_end": 1198, "summary": "종교적 신앙과 철학적 이성이 모순되지 않고 각자의 영역에서 진리를 추구한다는 주해를 저술하여 서유럽에 아리스토텔레스 철학 역수출.", "historical_significance": "13세기 서유럽 라틴 아베로에스주의와 르네상스 지적 각성의 불꽃."},
    {"id": "phi-027-thomas-aquinas-summa-theologiae", "title": "토마스 아퀴나스의 『신학대전(Summa Theologiae)』 (스콜라 철학의 정점)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1265, "year_end": 1274, "summary": "'은총은 자연을 파괴하지 않고 완성한다'며 아리스토텔레스 이성 철학과 기독교 계시 신학을 5대 신 존재 증명으로 완벽하게 조화.", "historical_significance": "가톨릭 교회의 공인 철학(토미즘)이자 중세 서양 철학의 최고봉."},
    {"id": "phi-028-chinul-don-o-jeom-su-korea", "title": "고려 지눌의 정혜쌍수(定慧雙修)와 돈오점수(頓悟漸修)", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1190, "year_end": 1210, "summary": "선종의 직관적 깨달음(돈오) 후에도 끊임없이 번뇌를 닦아나가는 점수(점진적 수행)와 선교 통합의 조계종 개창.", "historical_significance": "한국 불교를 대표하는 독보적인 조계종 수행 철학의 기틀."},
    {"id": "phi-029-william-of-ockham-razor-nominalism", "title": "윌리엄 오컴의 유명론(Nominalism)과 '오컴의 면도날' 법칙", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1320, "year_end": 1340, "summary": "보편자는 실재하지 않고 단지 이름(말)에 불과하며, 필요 이상으로 가정을 늘려서는 안 된다는 경제성의 원리(면도날) 제시.", "historical_significance": "중세 보편논쟁을 종식시키고 근대 경험론과 자연과학의 길을 연 분기점."},
    {"id": "phi-030-ibn-khaldun-muqaddimah-sociology", "title": "이븐 칼둔의 역사철학서 『무깟디마(역사서설)』와 아사비야(연대의식)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1377, "year_end": 1377, "summary": "유목민의 집단 연대감(아사비야)과 정주 도시 문명의 사치·부패로 인한 국가의 4단계 순환 흥망성쇠 법칙을 과학적으로 분석.", "historical_significance": "근대 사회학, 인구학, 역사철학의 진정한 선구자."},

    # --- Renaissance to Enlightenment (15th ~ 18th Century) ---
    {"id": "phi-031-machiavelli-the-prince-realpolitik", "title": "니콜로 마키아벨리의 『군주론(The Prince)』 (정치학과 도덕의 분리)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1513, "year_end": 1532, "summary": "'군주는 사자의 용맹과 여우의 간교함을 겸비해야 한다'며 중세 도덕주의적 환상을 깨고 현실 권력 정치(Realpolitik)의 메커니즘을 최초로 분석.", "historical_significance": "근대 정치학의 아버지."},
    {"id": "phi-032-thomas-more-utopia-critique", "title": "토머스 모어의 『유토피아(Utopia)』와 이상사회 구상", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1516, "year_end": 1516, "summary": "'양이 사람을 잡아먹는다'며 인클로저 운동을 비판하고 사유재산이 폐지된 공유 재산과 하루 6시간 노동의 평등 유토피아 섬 묘사.", "historical_significance": "근대 사회주의 및 비판적 사회철학의 효시."},
    {"id": "phi-033-francis-bacon-novum-organum-empiricism", "title": "프랜시스 베이컨의 『신기관(Novum Organum)』과 '아는 것이 힘이다'", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1620, "year_end": 1620, "summary": "4대 우상(종족·동굴·시장·극장)을 타파하고 자연 관찰과 실험을 통한 귀납법(Induction)으로 인간의 복지를 증진하는 지식 탐구 주창.", "historical_significance": "영국 경험론(Empiricism)과 근대 과학 방법론의 기수."},
    {"id": "phi-034-descartes-cogito-ergo-sum-rationalism", "title": "르네 데카르트의 방법적 회의와 '나는 생각한다, 고로 존재한다'", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1637, "year_end": 1641, "summary": "모든 것을 의심한 끝에 더 이상 의심할 수 없는 제1원리(Cogito)에 도달하고 정신과 물질을 구분한 심신이원론 확립.", "historical_significance": "근대 서양 합리론(Rationalism)과 주체성 철학의 아버지."},
    {"id": "phi-035-thomas-hobbes-leviathan-social-contract", "title": "토머스 홉스의 『리바이어던(Leviathan)』과 자연상태의 사회계약", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1651, "year_end": 1651, "summary": "국가가 없는 자연상태는 '만인의 만인에 대한 투쟁'이므로 생명 보존을 위해 절대 군주(리바이어던)에게 권력을 위임하는 계약을 맺는다고 주장.", "historical_significance": "근대 사회계약설과 주권 이론의 출발점."},
    {"id": "phi-036-spinoza-ethics-pantheism-substance", "title": "바뤼흐 스피노자의 『에티카(Ethica)』와 범신론('신 즉 자연')", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1677, "year_end": 1677, "summary": "신과 자연은 하나(Deus sive Natura)라는 일원론적 실체론을 기하학적 연역 방식으로 증명하고 지적 사랑(Amor Dei Intellectualis)을 통한 자유 제시.", "historical_significance": "자유사상가이자 범신론·현대 생태철학의 선구."},
    {"id": "phi-037-john-locke-two-treatises-liberalism", "title": "존 로크의 『통치론』과 자연권(생명·자유·재산) 및 저항권", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1689, "year_end": 1690, "summary": "인간은 백지상태(Tabula Rasa)로 태어나며, 정부가 시민의 기본권을 침해할 때 시민은 정부를 전복할 정당한 저항권이 있음을 천명.", "historical_significance": "근대 자유주의(Liberalism)와 미국 독립선언서의 헌법적 모태."},
    {"id": "phi-038-montesquieu-spirit-of-the-laws", "title": "몽테스키외의 『법의 정신』과 3권 분립(Separation of Powers)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1748, "year_end": 1748, "summary": "권력의 남용을 막고 시민의 자유를 보장하기 위해 국가 권력을 입법권, 행정권, 사법권으로 분립하고 견제와 균형을 이루어야 한다고 역설.", "historical_significance": "현대 민주주의 국가 헌법 체제의 필수 기본 원리."},
    {"id": "phi-039-voltaire-treatise-on-tolerance", "title": "볼테르의 『관용론(Treatise on Tolerance)』과 표현의 자유", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1763, "year_end": 1763, "summary": "칼라스 사건의 종교적 광신을 고발하며 '나는 당신의 말에 동의하지 않지만, 당신이 말할 권리를 위해 목숨 바쳐 싸우겠다'는 관용 정신 주창.", "historical_significance": "프랑스 계몽주의의 수장이자 인권·종교적 자유의 수호자."},
    {"id": "phi-040-rousseau-social-contract-general-will", "title": "장 자크 루소의 『사회계약론』과 일반의지(General Will)·국민주권", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1762, "year_end": 1762, "summary": "'인간은 자유롭게 태어났으나 도처에서 사슬에 묶여 있다'며 공동선(일반의지)에 바탕을 둔 직접 민주주의와 국민주권론 제시.", "historical_significance": "프랑스 대혁명(1789)의 직접적인 사상적 도화선."},
    {"id": "phi-041-yi-hwang-toegye-juri-philosophy", "title": "퇴계 이황의 주리론(主理論)과 『성학십도(聖學十圖)』", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1568, "year_end": 1568, "summary": "이(理)가 발하여 기(氣)가 따르는 이기호발설과 경(敬) 사상을 바탕으로 선조에게 10폭의 병풍 그림으로 성리학의 도덕적 정수를 바침.", "historical_significance": "'동방의 주자'로 불리며 일본 에도 유학(야마자키 안사이)에 지대한 영향."},
    {"id": "phi-042-yi-i-yulgok-jugi-philosophy", "title": "율곡 이이의 주기론(主氣論)과 『성학집요(聖學輯要)』·십만양병설", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1575, "year_end": 1583, "summary": "기는 발하고 이는 타는 기발이승일도설(氣發理乘一途說)과 이통기국(理通氣局)을 제창하고 현실 개혁(수미법, 양병) 강조.", "historical_significance": "조선 성리학의 실천적 현실 개혁 이론 완성."},
    {"id": "phi-043-wang-yangming-mind-innate-knowing", "title": "왕양명의 심즉리(心卽理)와 지행합일(知行合一)·양명학", "region_id": "CHINA", "category_id": "RELIGION", "importance": "A", "year_start": 1508, "year_end": 1527, "summary": "'마음이 곧 이치다'라며 타고난 양심(치양지)을 깨닫고 앎과 행함은 본래 하나라는 지행합일(知行合一)의 실천 철학 정립.", "historical_significance": "주자학의 교조주의를 타파한 동양 근대 주체적 실천 철학."},
    {"id": "phi-044-adam-smith-invisible-hand-wealth", "title": "애덤 스미스의 『국부론』과 시장 경제의 '보이지 않는 손'", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1776, "year_end": 1776, "summary": "개인의 합리적 이기심에 따른 경제 활동이 시장의 '보이지 않는 손'에 의해 사회 전체의 부를 증진시킨다는 자유방임주의 경제철학 체계화.", "historical_significance": "고전 자본주의 경제학의 탄생."},
    {"id": "phi-045-immanuel-kant-critique-of-pure-reason", "title": "임마누엘 칸트의 비판철학 (코페르니쿠스적 전환과 정언명령)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1781, "year_end": 1788, "summary": "경험론과 합리론을 종합하여 대상이 주관의 인식틀(선험적 시공간과 범주)에 맞춰진다는 인식론적 전환과 도덕적 의무론(정언명령) 확립.", "historical_significance": "근대 서양 철학의 최고 정점이자 독일 관념론의 문을 연 거장."},
    {"id": "phi-046-jeong-yak-yong-dasan-silhak", "title": "다산 정약용의 실학 집대성 (『목민심서』, 『경세유표』, 『흠흠신서』)", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1801, "year_end": 1818, "summary": "강진 유배 18년간 500여 권의 저술을 통해 전론(여전제·정전제 토지개혁), 지방관의 청렴 애민, 사법 개혁을 체계화한 실사구시 실학 완성.", "historical_significance": "조선 후기 비판적 근대 지성의 최고봉."},

    # --- 19th Century Philosophy (German Idealism, Materialism, Existentialism, Utilitarianism) ---
    {"id": "phi-047-hegel-phenomenology-dialectic", "title": "게오르크 헤겔의 『정신현상학』과 변증법(정·반·합)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1807, "year_end": 1821, "summary": "절대정신이 역사의 변증법적 발전(모순과 지양)을 통해 자유를 실현해 나간다는 독일 관념론의 거대한 체계 완성.", "historical_significance": "마르크스 유물론과 19~20세기 유럽 철학 전체에 결정적 영향."},
    {"id": "phi-048-schopenhauer-world-as-will", "title": "아르투어 쇼펜하우어의 『의지와 표상으로서의 세계』 (염세주의 철학)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1818, "year_end": 1818, "summary": "세계의 본질은 맹목적인 '살고자 하는 의지'이며 삶은 고통의 연속이므로 예술적 관조와 동양 불교적 해탈을 통해 구원받아야 함을 역설.", "historical_significance": "니체, 프로이트, 바그너에게 심대한 영향을 준 비합리주의 철학."},
    {"id": "phi-049-kierkegaard-either-or-existentialism", "title": "쇠렌 키에르케고르의 『이것이냐 저것이냐』와 실존주의(Existentialism)의 기원", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1843, "year_end": 1849, "summary": "헤겔의 추상적 체계에 맞서 '신 앞에 선 단독자'로서 미적·윤리적 단계를 넘어 결단과 신앙의 도약을 감행하는 주체적 실존 강조.", "historical_significance": "현대 실존주의 철학의 아버지."},
    {"id": "phi-050-bentham-utilitarianism-greatest-happiness", "title": "제러미 벤담의 양적 공리주의 ('최대 다수의 최대 행복')", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1789, "year_end": 1802, "summary": "행위의 옳고 그름은 그것이 낳는 쾌락과 고통의 총량(쾌락 계산법)에 따라 결정된다는 입법과 도덕의 공리주의 원리 확립.", "historical_significance": "현대 복지 경제학과 민주적 법 개혁의 토대."},
    {"id": "phi-051-john-stuart-mill-on-liberty-utilitarianism", "title": "존 스튜어트 밀의 『자유론(On Liberty)』과 질적 공리주의", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1859, "year_end": 1861, "summary": "'만족한 돼지보다 불만족한 소크라테스가 낫다'며 정신적 쾌락의 질을 중시하고, 타인에게 해를 끼치지 않는 한 절대적 사상·표현의 자유 보장(해악 원칙) 주창.", "historical_significance": "자유주의 민주주의 헌정 철학의 바이블."},
    {"id": "phi-052-marx-engels-communist-manifesto", "title": "카를 마르크스·프리드리히 엥겔스의 『공산당 선언』과 유물사관", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1848, "year_end": 1848, "summary": "'지금까지의 모든 역사는 계급투쟁의 역사이다'를 선언하며 자본주의 잉여가치 착취를 분석하고 노동자 계급의 국제적 단결과 혁명 제시.", "historical_significance": "20세기 전 세계 정치 지형을 바꾼 사회주의·공산주의 운동의 출발점."},
    {"id": "phi-053-friedrich-nietzsche-thus-spoke-zarathustra", "title": "프리드리히 니체의 '신은 죽었다'와 위버멘쉬(초인)·영겁회귀", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1882, "year_end": 1885, "summary": "기독교 노예도덕과 허무주의(Nihilism)를 망치로 부수고, 운명을 사랑하는 아모르 파티(Amor Fati)와 삶의 주인이 되는 위버멘쉬(Übermensch) 선언.", "historical_significance": "20세기 포스트모더니즘, 실존주의, 현대 사상의 불꽃."},
    {"id": "phi-054-sigmund-freud-interpretation-of-dreams", "title": "지그문트 프로이트의 『꿈의 해석』과 무의식(Unconscious)·정신분석학", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1899, "year_end": 1900, "summary": "인간의 행동을 지배하는 무의식의 영역, 이드(Id)·에고(Ego)·초자아(Superego)의 갈등과 리비도(성적 에너지)를 규명.", "historical_significance": "인간 심리학, 예술, 문학, 철학의 패러다임을 뒤흔든 정신분석학의 창시."},
    {"id": "phi-055-william-james-pragmatism-truth", "title": "윌리엄 제임스의 실용주의(Pragmatism) 선언", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1898, "year_end": 1907, "summary": "진리란 고정된 추상적 관념이 아니라 실제 인간 삶의 경험 속에서 유용한 현금 가치(Cash value)를 발휘할 때 참이 된다는 실용주의 제안.", "historical_significance": "미국을 대표하는 고유한 독자 철학 전통 확립."},

    # --- 20th & 21st Century Philosophy & Critical Thought ---
    {"id": "phi-056-max-weber-protestant-ethic", "title": "막스 베버의 『프로테스탄트 윤리와 자본주의 정신』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1904, "year_end": 1905, "summary": "칼뱅주의 예정설과 직업 소명 의식에 따른 금욕적 노동이 근대 합리적 자본주의 형성의 원동력이었음을 규명.", "historical_significance": "현대 사회과학과 비교종교학, 경제사회학의 최고 고전."},
    {"id": "phi-057-edmund-husserl-phenomenology", "title": "에드문트 후설의 현상학(Phenomenology)과 '사태 자체로!'", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1900, "year_end": 1913, "summary": "자연주의적 선입견을 판단중지(에포케)하고 의식의 지향성(Intentionality)을 통해 순수 의식에 직접 주어지는 본질을 직관.", "historical_significance": "하이데거, 사르트르, 메를로퐁티로 이어지는 20세기 대륙 철학의 뿌리."},
    {"id": "phi-058-martin-heidegger-being-and-time", "title": "마르틴 하이데거의 『존재와 시간(Sein und Zeit)』 (현존재 분석론)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1927, "year_end": 1927, "summary": "전통 서양 존재론의 '존재 망각'을 비판하고, 세계-내-존재이자 죽음을 향한 존재로서의 인간 현존재(Dasein)의 시간성을 규명.", "historical_significance": "20세기 실존철학과 해석학의 최고 기념비."},
    {"id": "phi-059-ludwig-wittgenstein-tractatus-investigations", "title": "루트비히 비트겐슈타인의 『논리철학논고』와 『철학적 탐구』 (언어철학)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1921, "year_end": 1953, "summary": "'말할 수 없는 것에 대해서는 침묵해야 한다'는 초기 그림이론과 언어는 삶의 형식 속에서의 규칙 따르기라는 후기 '언어게임' 이론.", "historical_significance": "20세기 분석철학과 일상언어학파를 창시한 천재 철학자."},
    {"id": "phi-060-karl-popper-falsificationism-open-society", "title": "칼 포퍼의 반증 가능성(Falsifiability)과 『열린 사회와 그 적들』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1934, "year_end": 1945, "summary": "과학적 이론은 반증될 수 있어야 하며, 플라톤·헤겔·마르크스의 역사주의 전체주의를 비판하고 비판적 합리주의에 기초한 열린 사회 옹호.", "historical_significance": "현대 과학철학과 자유민주주의 옹호론의 최고 고전."},
    {"id": "phi-061-jean-paul-sartre-existentialism-humanism", "title": "장 폴 사르트르의 『존재와 무』 ('실존은 본질에 앞선다')", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1943, "year_end": 1946, "summary": "인간은 정해진 본질 없이 세상에 던져졌으므로 스스로 선택하고 그 자유에 따르는 전적인 책임을 져야 한다는 앙가주망(사회참여) 실존주의.", "historical_significance": "20세기 프랑스 실존주의를 전 세계 지성계의 유행으로 이끈 기수."},
    {"id": "phi-062-albert-camus-myth-of-sisyphus", "title": "알베르 카뮈의 『시지프 신화』와 부조리(The Absurd)에의 반항", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1942, "year_end": 1951, "summary": "끝없이 바위를 굴려 올려야 하는 시지프처럼 삶이 무의미하고 부조리할지라도 자살하지 않고 매 순간 치열하게 반항하며 살아가는 인간 찬가.", "historical_significance": "부조리 철학과 노벨문학상에 빛나는 20세기 지성."},
    {"id": "phi-063-hannah-arendt-banality-of-evil", "title": "한나 아렌트의 '악의 평범성(Banality of Evil)' (『예루살렘의 아이히만』)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1958, "year_end": 1963, "summary": "수백만 명을 학살한 나치 관료 아이히만은 악마가 아니라 타인의 처지를 생각하지 못하는 '생각 없음(사유의 무능)'에서 악을 저질렀음을 고발.", "historical_significance": "현대 정치철학과 도덕적 사유의 필수 규범."},
    {"id": "phi-064-michel-foucault-discipline-and-punish", "title": "미셸 푸코의 권력-지식 담론과 『감시와 처벌』 (판옵티콘)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1961, "year_end": 1975, "summary": "근대 감옥, 병원, 학교가 규율 권력(규격화, 시선)을 통해 인간의 신체를 순종적으로 길들여왔음을 벤담의 원형감옥(판옵티콘)을 통해 해부.", "historical_significance": "구조주의 및 포스트모더니즘 권력 비판의 최고 거장."},
    {"id": "phi-065-jacques-derrida-deconstruction", "title": "자크 데리다의 해체주의(Deconstruction)와 차연(Différance)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1967, "year_end": 1972, "summary": "서구 전통의 음성중심주의와 이분법적 위계 구조(빛/어둠, 남/여)를 텍스트 내부의 모순을 통해 해체(Deconstruction)하고 의미의 끊임없는 지연 선언.", "historical_significance": "현대 문학 이론과 포스트구조주의 철학의 핵."},
    {"id": "phi-066-jurgen-habermas-communicative-action", "title": "위르겐 하버마스의 『의사소통행위이론』과 공론장(Public Sphere)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1962, "year_end": 1981, "summary": "도구적 이성의 폐해를 극복하기 위해 지배 없는 합리적 토론과 상호 이해를 지향하는 의사소통적 합리성과 심의 민주주의 제창.", "historical_significance": "프랑크푸르트 비판이론 제2세대의 대표 사상가."},
    {"id": "phi-067-john-rawls-theory-of-justice-veil", "title": "존 롤스의 『정의론(A Theory of Justice)』과 '무지의 베일'", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1971, "year_end": 1971, "summary": "자신의 계급·재능을 모르는 '무지의 베일' 가상 원초 상태에서 합의되는 기본적 자유의 평등(제1원칙)과 최소수혜자 최대이익(차등원칙) 제시.", "historical_significance": "현대 자유주의 정의론과 복지 국가 재분배 윤리의 절대적 기준."},
    {"id": "phi-068-antonio-gramsci-cultural-hegemony", "title": "안토니오 그람시의 『옥중수고』와 문화적 헤게모니(Hegemony) 이론", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1929, "year_end": 1935, "summary": "지배 계급은 물리적 폭력뿐 아니라 언론, 교육, 문화를 통해 피지배자의 자발적 동의를 얻어 통치하므로 진지전(진보적 문화 운동)이 필요함을 역설.", "historical_significance": "네오 마르크스주의와 현대 문화 연구의 핵심 이론."},
    {"id": "phi-069-michael-sandel-justice-communitarianism", "title": "마이클 샌델의 공동체주의(Communitarianism)와 『정의란 무엇인가』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1982, "year_end": 2009, "summary": "롤스의 연고 없는 개인주의를 비판하고, 공동체의 미덕과 역사적 유대 속에서 좋은 삶과 공공선(Common Good)을 추구하는 정치철학 제시.", "historical_significance": "현대 공동체주의 윤리학과 대중 정치철학의 세계적 신드롬."},
    {"id": "phi-070-peter-singer-animal-liberation-altruism", "title": "피터 싱어의 『동물 해방(Animal Liberation)』과 효율적 이타주의", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1975, "year_end": 2015, "summary": "고통을 느낄 수 있는 모든 생명체(동물)에 대한 종차별주의(Speciesism)를 비판하고 공리주의적 관점에서 동물 권리와 빈곤 퇴치 기부 실천 주장.", "historical_significance": "현대 응용윤리학과 비건·동물권 운동의 기폭제."},
    {"id": "phi-071-yuval-harari-sapiens-cognitive-revolution", "title": "유발 하라리의 『사피엔스』와 가상(허구)을 믿는 인지혁명", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 2011, "year_end": 2014, "summary": "호모 사피엔스가 지구를 지배하게 된 비결은 신, 국가, 돈, 인권 등 실재하지 않는 '허구의 이야기'를 수백만 명이 함께 믿고 협력한 인지혁명 덕분임을 규명.", "historical_significance": "21세기 인류학, 역사학, 미래학의 세계적 밀리언셀러."},
    {"id": "phi-072-choe-jeu-donghak-innaecheon", "title": "수운 최제우의 동학 창시와 인내천(人乃天, 사람이 곧 하늘이다)", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1860, "year_end": 1864, "summary": "서학(서구 열강)에 맞서 경주에서 시천주(侍天主)와 후천개벽을 선포하고 신분 귀천 없이 모든 인간이 하늘님을 모시고 있다는 절대 평등 사상 주창.", "historical_significance": "한국 근대 민중 해방과 동학농민혁명의 사상적 모태."},
    {"id": "phi-073-simone-de-beauvoir-second-sex", "title": "시몬 드 보부아르의 『제2의 성(The Second Sex)』 ('여성은 태어나는 것이 아니라 만들어진다')", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1949, "year_end": 1949, "summary": "가부장제 사회가 여성을 주체(남성)에 종속된 '타자'로 규정해왔음을 역사적·사회적으로 폭로하고 여성의 자율적 해방 선언.", "historical_significance": "현대 페미니즘 이론의 가장 위대한 고전."},
    {"id": "phi-074-thomas-kuhn-structure-scientific-revolutions", "title": "토머스 쿤의 『과학혁명의 구조』와 패러다임 전환(Paradigm Shift)", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1962, "year_end": 1962, "summary": "과학의 발전은 단순한 지식의 누적이 아니라 위기와 비합리적 혁명을 거쳐 지배적인 패러다임이 완전히 교체되는 불연속적 도약임을 증명.", "historical_significance": "과학철학 및 현대 지성계 모든 학문에 '패러다임' 용어 정착."},
    {"id": "phi-075-ham-seokheon-ssial-philosophy", "title": "함석헌의 씨알 사상과 『뜻으로 본 한국역사』", "region_id": "KOREA", "category_id": "RELIGION", "importance": "A", "year_start": 1950, "year_end": 1970, "summary": "왕조나 권력자가 아닌 민중(씨알)이 역사의 참된 주인이며 고난의 역사를 통해 인류 평화의 사명을 감당해야 한다는 비폭력 평화주의 철학.", "historical_significance": "한국 근현대 민주화 운동과 평화 사상의 영적 지주."},
    {"id": "phi-076-byung-chul-han-burnout-society", "title": "한병철의 『피로사회(The Burnout Society)』와 자기착취 비판", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 2010, "year_end": 2012, "summary": "규율사회의 금지('해서는 안 된다')에서 성과사회의 긍정 과잉('할 수 있다')으로 전환되며 스스로를 착취해 번아웃에 빠지는 현대인 진단.", "historical_significance": "21세기 신자유주의 성과주의를 날카롭게 해부한 세계적 베스트셀러 철학."},
    {"id": "phi-077-ulrich-beck-risk-society", "title": "울리히 벡의 『위험사회(Risk Society)』와 성찰적 근대화", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1986, "year_end": 1986, "summary": "원전 사고(체르노빌), 환경 파괴, 기후 위기 등 근대 산업화의 성공 자체가 통제 불가능한 글로벌 위험을 낳고 있음을 경고.", "historical_significance": "현대 생태주의와 위험 관리 거버넌스의 기본 교본."},
    {"id": "phi-078-slavoj-zizek-sublime-object-ideology", "title": "슬라보예 지젝의 『이데올로기의 숭고한 대상』과 라캉주의 비판", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 1989, "year_end": 2000, "summary": "'사람들은 그것이 거짓임을 알면서도 그대로 행한다'는 시니컬한 현대 이데올로기 작동 방식을 라캉의 정신분석과 대중문화로 통렬히 폭로.", "historical_significance": "현대 급진 철학의 최고 엔터테이너이자 비판적 지성."},
    {"id": "phi-079-judith-butler-gender-trouble", "title": "주디스 버틀러의 『젠더 트러블(Gender Trouble)』과 젠더 수행성", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1990, "year_end": 1990, "summary": "생물학적 성(Sex)조차 자연적인 것이 아니며 젠더(Gender)는 사회적 규범의 반복적인 수행(Performativity)을 통해 구성된 환상임을 주장.", "historical_significance": "현대 퀴어 이론(Queer Theory)과 제3세대 페미니즘의 기틀."},
    {"id": "phi-080-frantz-fanon-wretched-of-the-earth", "title": "프란츠 파농의 『대지의 저주받은 자들』과 탈식민주의(Postcolonialism)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1961, "year_end": 1961, "summary": "서구 제국주의의 식민 통치가 피식민자의 정신과 신체를 어떻게 파괴했는지 정신의학적으로 분석하고 해방 투쟁을 정당화.", "historical_significance": "알제리 해방과 제3세계 탈식민주의 저항 운동의 성서."},
    {"id": "phi-081-edward-said-orientalism", "title": "에드워드 사이드의 『오리엔탈리즘(Orientalism)』과 서구 제국주의 비판", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1978, "year_end": 1978, "summary": "서양이 동양(오리엔트)을 신비롭고 열등하며 수동적인 타자로 타자화하여 지배를 정당화해 온 문화적 담론 구조를 고발.", "historical_significance": "탈식민주의 문화 비평 및 비교문학의 패러다임 전환."},
    {"id": "phi-082-gilles-deleuze-anti-oedipus-rhizome", "title": "질 들뢰즈·펠릭스 가타리의 『안티 오이디푸스』와 리좀(Rhizome) 철학", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 1972, "year_end": 1980, "summary": "뿌리 형태의 중심적 위계 구조를 거부하고 수평적으로 뻗어나가 접속하는 리좀(줄기) 네트워크와 욕망의 유목민(노마드) 주체론 제안.", "historical_significance": "디지털 인터넷망과 다원주의 사상의 철학적 모델."},
    {"id": "phi-083-martin-buber-i-and-thou", "title": "마르틴 부버의 『나와 너(I and Thou)』와 대화 철학", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 1923, "year_end": 1923, "summary": "타자를 도구로 대하는 '나-그것(I-It)'의 관계를 극복하고, 영혼과 영혼이 인격적으로 마주하는 진정한 '나-너(I-Thou)'의 실존적 만남 역설.", "historical_significance": "현대 종교철학, 교육학, 심리치료의 윤리적 기둥."},
    {"id": "phi-084-viktor-frankl-mans-search-for-meaning", "title": "빅터 프랭클의 『죽음의 수용소에서』와 의미치료(Logotherapy)", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 1946, "year_end": 1946, "summary": "아우슈비츠 강제수용소의 생지옥 속에서도 '왜 살아야 하는지 아는 사람은 어떤 고통도 견뎌낸다'며 삶의 의미를 찾는 로고테라피 창안.", "historical_significance": "인류 고통 극복과 회복 탄력성의 가장 감동적인 심리 철학."},
    {"id": "phi-085-john-dewey-democracy-and-education", "title": "존 듀이의 『민주주의와 교육(Democracy and Education)』과 도구주의", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1916, "year_end": 1916, "summary": "주입식 교육을 배격하고 행함으로써 배우는(Learning by Doing) 경험 중심 진보주의 교육과 삶의 방식으로서의 참여 민주주의 주창.", "historical_significance": "현대 공교육과 실천적 민주주의 철학의 기틀."},
    {"id": "phi-086-george-herbert-mead-mind-self-society", "title": "조지 허버트 미드의 상징적 상호작용론 (자아와 사회)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1934, "year_end": 1934, "summary": "인간의 자아(Self)는 타고난 것이 아니라 타인과의 상징적 언어 상호작용과 '일반화된 타자(Generalized Other)'의 시선을 내면화하며 형성됨을 규명.", "historical_significance": "미국 사회심리학과 미시사회학의 정립자."},
    {"id": "phi-087-walter-benjamin-work-of-art-mechanical", "title": "발터 벤야민의 『기계복제시대의 예술작품』과 아우라(Aura)의 붕괴", "region_id": "WEST", "category_id": "ART_CULTURE", "importance": "A", "year_start": 1935, "year_end": 1936, "summary": "사진과 영화 같은 대량 복제 기술로 예술의 고유한 신비성(아우라)은 사라졌으나 대중의 비판적 수용과 예술의 민주화가 열렸음을 분석.", "historical_significance": "현대 미디어 이론과 문화비평의 최고 고전."},
    {"id": "phi-088-theodor-adorno-dialectic-of-enlightenment", "title": "아도르노·호르크하이머의 『계몽의 변증법』과 문화산업 비판", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1944, "year_end": 1947, "summary": "자연의 공포에서 벗어나려던 계몽 이성이 도구적 합리성으로 변질되어 아우슈비츠와 대중 기만의 문화산업(Culture Industry)을 낳았음을 통렬히 비판.", "historical_significance": "프랑크푸르트학파 비판이론(Critical Theory)의 출발점."},
    {"id": "phi-089-richard-rorty-philosophy-mirror-nature", "title": "리처드 로티의 『철학과 자연의 거울』과 신실용주의", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 1979, "year_end": 1979, "summary": "마음이 객관적 실재를 있는 그대로 비추는 '거울'이라는 서양 인식론적 환상을 해체하고, 진리 대신 연대성과 민주적 대화(에디피케이션)를 제안.", "historical_significance": "20세기 후반 미국 철학을 재정의한 네오 프래그머티즘의 기수."},
    {"id": "phi-090-charles-taylor-sources-of-the-self", "title": "찰스 테일러의 『자아의 원천들(Sources of the Self)』과 다문화주의", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1989, "year_end": 1994, "summary": "근대 도덕적 정체성의 형성을 탐구하고 소수 집단의 정체성과 문화를 동등하게 존중해야 한다는 '인정의 정치(Politics of Recognition)' 주창.", "historical_significance": "현대 다문화주의와 정치철학의 필독서."},
    {"id": "phi-091-amartya-sen-development-as-freedom", "title": "아마르티아 센의 역량 접근법(Capability Approach)과 『자유로서의 발전』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1999, "year_end": 1999, "summary": "단순한 GDP 성장이 아니라 인간이 가치 있다고 여기는 삶을 영위할 실질적 역량(교육, 건강, 자유)을 확장하는 것이 진정한 발전임을 역설(1998 노벨경제학상).", "historical_significance": "UN 인간개발지수(HDI)의 이론적 기초."},
    {"id": "phi-092-axell-honneth-struggle-for-recognition", "title": "악셀 호네트의 『인정투쟁(The Struggle for Recognition)』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1992, "year_end": 1995, "summary": "사랑(자신감), 권리(자존감), 연대(자긍심)의 3단계 상호 인정이 인간의 온전한 정체성에 필수적이며 무시당함이 사회적 저항을 낳음을 규명.", "historical_significance": "프랑크푸르트학파 3세대 인정 중심 비판이론 정립."},
    {"id": "phi-093-g-a-cohen-why-not-socialism", "title": "G. A. 코헨의 분석마르크스주의와 평등주의 철학", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "B", "year_start": 1978, "year_end": 2009, "summary": "영미 분석철학의 엄밀한 논리를 적용하여 마르크스 유물론을 재해석하고 자발적 연대와 기회 평등의 사회주의적 이상 옹호.", "historical_significance": "영미 분석 마르크스주의의 최고 지성."},
    {"id": "phi-094-quentin-meillassoux-after-finitude", "title": "퀭탱 메이야수의 『유한성 이후』와 사변적 실재론(Speculative Realism)", "region_id": "WEST", "category_id": "RELIGION", "importance": "B", "year_start": 2006, "year_end": 2008, "summary": "인간의 사유와 대상의 상관관계를 넘어서 인간 이전의 화석(선조성)처럼 인간 의식과 무관하게 존재하는 객관적 실재를 탐구.", "historical_significance": "21세기 탈인간중심주의 사변적 실재론 철학의 기폭제."},
    {"id": "phi-095-donna-haraway-cyborg-manifesto", "title": "도나 해러웨이의 『사이보그 선언(A Cyborg Manifesto)』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 1985, "year_end": 1991, "summary": "인간/기계, 자연/문화, 남성/여성의 이분법적 본질주의를 거부하고 경계가 해체된 하이브리드 '사이보그' 정체성을 통해 해방 모색.", "historical_significance": "포스트휴머니즘과 테크노페미니즘의 불후의 명저."},
    {"id": "phi-096-bruno-latour-we-have-never-been-modern", "title": "브뤼노 라투르의 행위자-연결망 이론(ANT)과 『우리는 결코 근대인이었던 적이 없다』", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 1991, "year_end": 2005, "summary": "자연과 사회를 인위적으로 분리한 근대주의를 비판하고 인간과 비인간(미생물, 기계, 바이러스)이 평등하게 상호작용하는 네트워크로서 세상 규명.", "historical_significance": "현대 인류세(Anthropocene) 철학과 과학사회학의 최고 석학."},
    {"id": "phi-097-nick-bostrom-superintelligence-ai-ethics", "title": "닉 보스트롬의 『슈퍼인텔리전스』와 인공지능(AI) 실존적 위험 및 윤리", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 2014, "year_end": 2016, "summary": "인간 지능을 뛰어넘는 초지능 AI가 인류의 가치와 정렬(Alignment)되지 못할 경우 닥칠 실존적 위협을 경고하고 AI 안전 윤리 표준 제시.", "historical_significance": "21세기 생성형 AI 시대 인류 존망을 다루는 AI 윤리학의 필독서."},
    {"id": "phi-098-shoshana-zuboff-surveillance-capitalism", "title": "쇼샤나 주보프의 『감시 자본주의의 시대(The Age of Surveillance Capitalism)』", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 2019, "year_end": 2019, "summary": "빅테크 기업들이 사용자의 행동 잉여 데이터를 무단 채굴하여 행동 수정 상품으로 판매하는 새로운 형태의 디지털 감시 권력 폭로.", "historical_significance": "디지털 플랫폼 독점과 데이터 주권 침해에 대한 21세기 최고의 비판적 분석."},
    {"id": "phi-099-michael-sandels-tyranny-of-merit", "title": "마이클 샌델의 『공정하다는 착각(The Tyranny of Merit)』 (능력주의의 덫)", "region_id": "WEST", "category_id": "INSTITUTION", "importance": "A", "year_start": 2020, "year_end": 2020, "summary": "자신의 성공이 오직 자신의 노력 때문이라는 능력주의의 오만이 패자에게 굴욕을 안기고 사회적 양극화와 포퓰리즘을 낳았음을 고발하고 겸손과 연대 촉구.", "historical_significance": "현대 교육과 노동, 분배 정의에 대한 가장 뜨거운 담론."},
    {"id": "phi-100-dipesh-chakrabarty-climate-history", "title": "디페시 차크라바르티의 인류세(Anthropocene) 역사철학과 지구적 공존 윤리", "region_id": "WEST", "category_id": "RELIGION", "importance": "A", "year_start": 2009, "year_end": 2021, "summary": "인간의 행위가 지구 지질학적 힘이 된 인류세 시대에 인간 중심의 역사를 넘어 지구 생명 시스템 전체와의 공존을 도모하는 새로운 지구적 역사철학 주창.", "historical_significance": "기후 위기 시대 21세기 인류 문명의 생존을 위한 철학적 대전환."}
]

def export_philosophy_100():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_path = os.path.join(base_dir, "data", "themes", "philosophy_100.json")
    
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump({
            "theme": "PHILOSOPHY_AND_THOUGHT",
            "title": "역사상 가장 위대한 철학·사상·주의 마일스톤 100선 (Ancient to Modern)",
            "count": len(PHILOSOPHY_100),
            "events": PHILOSOPHY_100
        }, f, ensure_ascii=False, indent=2)
        
    print(f"✅ Generated {len(PHILOSOPHY_100)} Philosophy & Thought events -> {target_path}")

if __name__ == "__main__":
    export_philosophy_100()
