#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Landmark Historical Events of Latin America, Africa, and Asia (South Asia, Southeast Asia, Japan, Islamic World)
into data/seed/historical_events.json under region_id = 'OTHER_REGIONS'.
"""

import json
import os

SEED_FILE = os.path.join(os.path.dirname(__file__), "..", "data", "seed", "historical_events.json")

GLOBAL_EVENTS = [
    # --- 1. 고대 (Ancient & Classical: BC 30C ~ BC 1C) ---
    {
        "id": "global-indus-valley-mohenjodaro",
        "title": "인더스 문명 발흥과 모헨조다로·하라파의 도시 계획",
        "title_en": "Indus Valley Civilization & Urban Planning of Mohenjo-daro",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "SCIENCE",
        "importance": "A",
        "year_start": -2600,
        "year_end": -1900,
        "date_precision": "range",
        "summary": "인더스강 유역에서 정밀한 격자형 도로망, 벽돌 배수관, 공중목욕탕(대목욕장), 표준화된 도량형을 갖춘 인류 최초의 계획도시 문명 번영.",
        "detailed_description": "기원전 2600년경부터 인도 아대륙의 인더스강과 가가르-하크라강 유역에서 고도로 발전된 청동기 도시 문명인 인더스 문명이 꽃피웠습니다.\n\n모헨조다로와 하라파 등 주요 도시는 완벽한 격자형 도로망과 구운 벽돌 건축, 정교한 지하 하수도 및 정화조 시스템, 공중목욕탕을 갖춘 놀라운 토목 공학적 성취를 보여주었습니다. 인더스 문자는 아직 완전히 해독되지 않았으나, 수천 점의 인장과 정밀한 도량형 유물은 메소포타미아와의 활발한 원거리 해상 교역을 입증합니다.\n\n이 문명은 사제 계급 중심의 평화로운 자치 도시 모델을 보여주었으며, 기원전 1900년경 기후 변화(몬순 약화 및 가뭄)와 유로 변경으로 쇠퇴하기까지 남아시아 문명의 깊은 기틀이 되었습니다.",
        "historical_significance": "인류 역사상 가장 선진적인 고대 도시 위생·토목 공학 모델이자 남아시아 최초의 도시 문명.",
        "cause": "인더스강의 비옥한 충적 평야 농업 생산성과 청동기 야금술, 메소포타미아와의 교역망 확대.",
        "consequence": "남아시아 도시화의 원형 형성 및 이후 베다 시대로 이어지는 문화적 기층 형성.",
        "confidence": "HIGH",
        "sources": [{"title": "Ancient South Asian Civilizations (Oxford History)"}]
    },
    {
        "id": "global-olmec-civilization",
        "title": "올멕 문명(Olmec) 발흥과 거대 두상 조각",
        "title_en": "Rise of Olmec Civilization & Colossal Stone Heads",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 멕시코",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": -1200,
        "year_end": -400,
        "date_precision": "range",
        "summary": "멕시코 걸프만 연안의 산로렌소와 라벤타를 중심으로 옥 장식, 흙 피라미드, 20톤에 달하는 거대 현무암 두상 조각을 남긴 메소아메리카 문명의 모태.",
        "detailed_description": "기원전 1200년경 멕시코 남동부 열대 저지대에서 '어머니 문명(Mother Culture)'으로 불리는 올멕 문명이 발흥하였습니다.\n\n산로렌소와 라벤타 유적에서 발견된 최대 3m, 무게 20톤 이상의 거대 현무암 두상 조각(Colossal Heads)은 군주이자 사제였던 통치자들의 위엄을 드러냅니다. 올멕인들은 고무나무 수액을 이용해 고무공 경기를 창시하였으며, 재규어 신앙, 옥(Jade) 조각, 인공 제방과 토축 피라미드를 축조하였습니다.\n\n올멕 문명이 창안한 천문 역법과 상형문자의 원형, 종교적 세계관은 이후 마야, 테오티우아칸, 아즈텍 등 메소아메리카의 모든 후속 문명으로 계승되었습니다.",
        "historical_significance": "아메리카 대륙 최초의 복합 제정일치 문명이자 메소아메리카 전 문명의 기원이 된 모체 문명.",
        "cause": "걸프만 유역의 풍부한 옥수수 농경 생산성과 종교적 권력 엘리트의 집약.",
        "consequence": "마야, 사포텍, 아즈텍 문명의 문자, 역법, 건축 양식의 원형 확립.",
        "confidence": "HIGH",
        "sources": [{"title": "The Olmec World: Ritual and Rulership"}]
    },
    {
        "id": "global-carthage-maritime-empire",
        "title": "카르타고(Carthage) 해상 제국 건설과 서지중해 무역망 장악",
        "title_en": "Rise of Carthage Maritime Empire & Western Mediterranean Trade",
        "region_id": "OTHER_REGIONS",
        "sub_region": "아프리카 / 튀니지",
        "category_id": "ECONOMY",
        "importance": "A",
        "year_start": -814,
        "year_end": -146,
        "date_precision": "range",
        "summary": "북아프리카 튀니스만 연안에 건설된 페니키아계 도시국가 카르타고가 강력한 갤리선 해군과 은·주석 무역망으로 서지중해 패권 장악.",
        "detailed_description": "기원전 814년 페니키아 티레의 디도 여왕에 의해 건설된 카르타고는 북아프리카의 전략적 요충지를 바탕으로 지중해 최대의 상업 해상 제국으로 성장하였습니다.\n\n시칠리아, 사르데냐, 이베리아반도 남부에 이르는 방대한 상업 식민지를 개척하고, 이베리아의 풍부한 은광과 북유럽의 주석, 아프리카의 황금과 상아를 독점 유통하였습니다. 원형 군항 코톤(Cothon)과 5단 노선(Quinquereme) 해군력을 바탕으로 지중해의 해상 무역로를 완벽히 통제하였습니다.\n\n기원전 3세기 로마와의 3차례에 걸친 포에니 전쟁에서 한니발 바르카 장군이 알프스를 넘어 로마 본토를 위협하는 등 고대 지중해 패권을 둘러싼 세기의 대결을 펼쳤습니다.",
        "historical_significance": "북아프리카 최초의 글로벌 해상 상업 제국이자 고대 서양과 아프리카를 잇는 교역 허브.",
        "cause": "페니키아 본토의 쇠퇴와 카르타고의 지리적 해상 교역 요충지 선점.",
        "consequence": "포에니 전쟁을 통한 로마의 지중해 단독 패권 확립 및 헬레니즘-셈족 문화 융합.",
        "confidence": "HIGH",
        "sources": [{"title": "Carthage Must Be Destroyed (Richard Miles)"}]
    },
    {
        "id": "global-buddhism-gautama-buddha",
        "title": "석가모니(고타마 싯다르타)의 불교 창시와 사성제 설파",
        "title_en": "Gautama Buddha's Enlightenment & Foundation of Buddhism",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "RELIGION",
        "importance": "A",
        "year_start": -563,
        "year_end": -483,
        "date_precision": "range",
        "summary": "샤카족 왕자 싯다르타가 보리수 아래에서 깨달음을 얻고 브라만교의 카스트와 희생제를 비판하며 자비와 해탈의 불교 창시.",
        "detailed_description": "기원전 6세기 인도 카필라바스투의 왕자 고타마 싯다르타는 생로병사의 고통을 목격하고 출가하여, 붓다가야의 보리수 아래에서 궁극적인 깨달음을 얻고 '붓다(Buddha, 깨달은 자)'가 되었습니다.\n\n초전법륜을 통해 인생의 본질을 고(苦)로 인식하고 고통의 소멸에 이르는 길인 사성제(四聖諦)와 팔정도(八正道), 만물의 상호의존성을 밝힌 연기설(緣起說)을 설파하였습니다. 당시 브라만 중심의 엄격한 카스트 계급제와 동물 희생제를 정면으로 비판하고 만인의 평등과 생명 존중을 선언하였습니다.\n\n불교는 이후 아소카 대왕과 쿠샨 제국을 거쳐 동아시아(중국·한국·일본)와 동남아시아로 확산되며 아시아 문명 전체의 정신적·문화적 근간이 되었습니다.",
        "historical_significance": "축의 시대(Axial Age) 인류 보편 철학의 정점이자 동아시아와 동남아 문명을 규정한 세계 종교의 탄생.",
        "cause": "갠지스강 유역 도시화와 상인 계급 성장에 따른 브라만 카스트 특권에 대한 비판적 성찰.",
        "consequence": "범아시아적 불교 문화권 형성 및 건축·철학·미술(불상)의 혁신적 발전.",
        "confidence": "HIGH",
        "sources": [{"title": "What the Buddha Taught (Walpola Rahula)"}]
    },
    {
        "id": "global-maurya-ashoka-edicts",
        "title": "마우리아 제국 아소카 대왕의 인도 통일과 비폭력 불교 정치",
        "title_en": "Emperor Ashoka's Unification of India & Edicts on Non-Violence",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": -268,
        "year_end": -232,
        "date_precision": "range",
        "summary": "칼링가 전쟁의 참상을 반성하고 불교에 귀의하여 전 인도에 석주 칙령을 세우고 다르마(법)에 의한 평화 통치와 해외 포교 추진.",
        "detailed_description": "기원전 3세기 찬드라굽타 마우리아의 손자인 아소카 대왕은 인도 아대륙의 남단을 제외한 전 지역을 최초로 대통일하였습니다.\n\n그러나 기원전 261년 칼링가 정복 전쟁에서 10만 명이 학살되고 15만 명이 추방되는 참상을 목격한 후 깊은 회한에 빠져 불교에 귀의하고 무력 정복 대신 '다르마(Dharma, 정의와 도덕률)에 의한 정복'을 선포하였습니다. 제국 전역의 바위와 석주에 브라흐미 문자로 칙령(Edicts of Ashoka)을 새겨 생명 존중, 종교적 관용, 사회 복지(병원·도로·식수대 설립)를 제도화하였습니다.\n\n아소카는 스리랑카, 동남아, 헬레니즘 서아시아로 불교 사절단을 파견하여 불교를 인도 로컬 종교에서 세계 종교로 도약시켰습니다.",
        "historical_significance": "인도 최초의 대통일 제국이자 인류 역사상 최초의 비폭력·도덕주의적 제국 통치 모델 확립.",
        "cause": "마우리아 제국의 군사 팽창과 칼링가 전쟁의 참혹성에 대한 황제의 윤리적 각성.",
        "consequence": "스리랑카·동남아·중앙아시아로의 불교 세계화 및 사자상(현 인도 국장) 등 석조 예술 번영.",
        "confidence": "HIGH",
        "sources": [{"title": "Ashoka in Ancient India (Nayanjot Lahiri)"}]
    },
    {
        "id": "global-teotihuacan-pyramid-sun",
        "title": "테오티우아칸(Teotihuacan) 거대 도시와 태양의 피라미드 번영",
        "title_en": "Teotihuacan Metropolis & the Pyramid of the Sun",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 멕시코",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": -100,
        "year_end": 650,
        "date_precision": "range",
        "summary": "15만 명이 거주한 신대륙 최대 계획도시로, '죽은 자의 길'을 따라 높이 65m 태양의 피라미드와 달의 피라미드, 깃털 달린 뱀 신전 축조.",
        "detailed_description": "기원전 1세기부터 멕시코 중앙 고원에 건설된 테오티우아칸은 격자형 도로망과 복합 아파트형 주거지, 흑요석 공방을 갖춘 인구 15만의 거대 메가시티였습니다.\n\n남북으로 뻗은 4km의 '죽은 자의 길(Avenue of the Dead)' 축을 따라 밑변 225m, 높이 65m에 달하는 거대한 태양의 피라미드와 달의 피라미드가 위용을 자랑합니다. 군사적·상업적 영향력을 과테말라 마야 도시 티칼까지 뻗쳤으며, 깃털 달린 뱀 신(케찰코아틀) 신앙의 중심지가 되었습니다.",
        "historical_significance": "콜럼버스 이전 아메리카 대륙 최초의 거대 다민족 계획도시이자 신성 건축의 정점.",
        "cause": "중앙 멕시코 고원의 흑요석 광산 독점과 종교적 성지로서의 순례자 유입.",
        "consequence": "이후 톨텍 및 아즈텍 문명의 종교적 성지이자 도시 설계 롤모델 확립.",
        "confidence": "HIGH",
        "sources": [{"title": "Teotihuacan: City of the Gods"}]
    },

    # --- 2. 고대 제국 & 중세 (AD 1C ~ AD 13C) ---
    {
        "id": "global-kushan-gandhara-art",
        "title": "쿠샨 제국(Kushan)의 간다라 미술과 동서 대승불교 융합",
        "title_en": "Kushan Empire: Gandhara Greco-Buddhist Art & Silk Road Trade",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아·중앙아시아",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": 30,
        "year_end": 375,
        "date_precision": "range",
        "summary": "카니슈카 왕 시기 로마, 중국 한나라, 인도를 잇는 실크로드 길목에서 헬레니즘 조각 양식과 불교가 융합된 최초의 인간 형상 불상 창조.",
        "detailed_description": "1세기 중앙아시아에서 북인도로 진출한 쿠샨 제국은 로마 제국과 한나라 사이의 오아시스 실크로드와 인도양 해상 무역로를 통제하며 막대한 부를 축적하였습니다.\n\n카니슈카 1세 통치기 그리스 헬레니즘 조각 기법(물결치는 옷 주름, 아폴론 스타일의 이목구비)을 불교에 접목하여, 이전까지 발자국이나 바퀴로만 상징되던 붓다를 인간의 형상으로 조각한 '간다라 미술(Gandhara Art)'을 창시하였습니다. 대승불교(Mahayana) 교리를 집대성한 제4차 불교 결집을 후원하고 실크로드를 통해 중국과 동아시아로 불교를 전파하는 가교 역할을 하였습니다.",
        "historical_significance": "동양의 불교 사상과 서양의 그리스 헬레니즘 예술이 완벽히 조우한 인류 문명 융합의 상징.",
        "cause": "실크로드 중계 무역의 번영과 다문화 다종교 포용 정책.",
        "consequence": "중국, 한국, 일본 불상 예술의 직접적 기원 확립 및 대승불교의 동아시아 전파.",
        "confidence": "HIGH",
        "sources": [{"title": "The Crossroads of Asia (Joe Cribb)"}]
    },
    {
        "id": "global-gupta-empire-golden-age",
        "title": "굽타 제국(Gupta)의 인도 고전 르네상스와 '0'의 수학 발견",
        "title_en": "Gupta Empire: Golden Age of Indian Mathematics, Zero & Classical Sanskrit",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "SCIENCE",
        "importance": "A",
        "year_start": 320,
        "year_end": 550,
        "date_precision": "range",
        "summary": "찬드라굽타 2세 치세에 아리아바타의 0과 십진법 수학, 원주율 계산, 삼각법 창시, 칼리다사의 산스크리트 문학 및 아잔타 석굴 벽화 만개.",
        "detailed_description": "4~6세기 북인도를 통일한 굽타 왕조 시기는 인도 고전 문명과 과학의 황금기였습니다.\n\n천문학자 아리아바타(Aryabhata)와 브라마굽타는 '0(Zero)'의 사칙연산 규칙과 십진 위치 기수법을 체계화하고 지구가 자전한다는 지동설과 원주율(π=3.1416)을 계산하였습니다. 이 인도 수학 체계는 아랍을 거쳐 오늘날 전 세계가 사용하는 '아라비아 숫자'의 모태가 되었습니다. 《마하바라타》와 《라마야나》 서사시가 산스크리트어로 최종 정비되었으며, 아잔타 석굴 사원의 정교한 벽화와 조각이 완성되었습니다.",
        "historical_significance": "현대 디지털 수학의 기초인 '0'과 십진법을 인류에 선사한 남아시아 과학·예술 르네상스.",
        "cause": "정치적 안정과 갠지스 유역 상업 번영, 날란다 대학 등 고등 학술 기관 육성.",
        "consequence": "이슬람 및 서양 근대 수학 혁명의 직접적 모태 제공, 힌두교 문화의 고전적 표준 완성.",
        "confidence": "HIGH",
        "sources": [{"title": "A History of Ancient and Early Medieval India (Upinder Singh)"}]
    },
    {
        "id": "global-aksum-christianity-monuments",
        "title": "에티오피아 악숨 왕국(Aksum)의 기독교 국교화와 오벨리스크 번영",
        "title_en": "Kingdom of Aksum: Christianization & Giant Monolithic Stelae",
        "region_id": "OTHER_REGIONS",
        "sub_region": "아프리카 / 에티오피아",
        "category_id": "RELIGION",
        "importance": "A",
        "year_start": 330,
        "year_end": 356,
        "date_precision": "range",
        "summary": "에자나 왕 통치기 로마·페르시아·중국과 비견된 홍해 무역 강국 악숨이 기독교를 국교로 선포하고 거대 단일 석조 오벨리스크 건립.",
        "detailed_description": "4세기 에티오피아 고원의 악숨 왕국은 홍해의 항구 아둘리스를 통해 로마 제국, 인도, 사산조 페르시아를 잇는 해상 무역의 핵심 허브였습니다.\n\n에자나 왕(Ezana)은 서기 330년경 기독교를 국교로 채택하여 금화에 십자가를 주조하였으며, 이는 로마 제국과 거의 동시대에 이루어진 역사적 사건이었습니다. 악숨은 독자적인 게에즈(Ge'ez) 문자를 발전시켰으며, 높이 24m, 무게 160톤에 달하는 단일 석조 거대 스텔레(오벨리스크)를 세워 왕실의 권위를 과시하였습니다.\n\n악숨 왕국의 기독교 전통은 이후 랄리벨라 암굴 교회군으로 계승되며 아프리카 대륙에서 1700년 이상 단절되지 않고 이어진 독보적인 에티오피아 정교회 문화의 뿌리가 되었습니다.",
        "historical_significance": "고대 세계 4대 강국으로 평가받은 사하라 이남 아프리카의 찬란한 기독교 문명.",
        "cause": "홍해-인도양 해상 무역망의 번영과 시리아 기독교 성직자 프루멘티우스의 전도.",
        "consequence": "에티오피아 정교회의 독자적 발전 및 중세 동아프리카 기독교 왕국의 기틀 마련.",
        "confidence": "HIGH",
        "sources": [{"title": "Ancient African Civilizations: Aksum (Stuart Munro-Hay)"}]
    },
    {
        "id": "global-maya-classical-golden-age",
        "title": "마야 고전기 문명의 황금기와 정밀 역법·상형문자 체계",
        "title_en": "Classic Maya Golden Age: Mathematics, Calendar & Hieroglyphs",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 과테말라·멕시코",
        "category_id": "SCIENCE",
        "importance": "A",
        "year_start": 250,
        "year_end": 900,
        "date_precision": "range",
        "summary": "티칼, 팔렝케, 코판 등 거대 도시국가를 중심으로 0의 개념 수학, 20진법, 365일 정밀 태양력, 정교한 상형문자 및 계단식 피라미드 번영.",
        "detailed_description": "서기 3세기부터 9세기까지 유카탄반도와 과테말라의 열대 우림에서 마야 고전기 문명이 절정에 달했습니다.\n\n마야인들은 인도보다 앞서 '0(Zero)'의 수학적 개념을 발견하고 정밀한 20진법 체계를 확립하였으며, 금성의 공전 궤도와 일식·월식을 수백 년 단위로 정확히 예측하는 촐킨(260일력)과 하압(365일력), 장기력(Long Count) 체계를 구축하였습니다. 800여 개 기호로 이루어진 정교한 마야 상형문자로 왕실의 역사와 종교 의례를 석비와 필사본에 기록하였습니다.\n\n티칼 1호 신전 피라미드와 팔렝케 비문 신전 등 거대한 석조 건축물은 마야 천문학과 신성 국왕(K'uhul Ajaw) 제정일치 권력의 정점을 보여줍니다.",
        "historical_significance": "신대륙에서 가장 고도화된 수학·천문학·문자 체계를 완성한 아메리카 고전 문명의 금자탑.",
        "cause": "정교한 계단식 밭(테라스) 농업과 저수지 관개 시설, 도시국가 간 교역망 활성화.",
        "consequence": "메소아메리카 전역에 천문·역법 지식 전파 및 치첸이트사 후고전기 마야로 계승.",
        "confidence": "HIGH",
        "sources": [{"title": "The Maya (Michael D. Coe)"}]
    },
    {
        "id": "global-japan-shotoku-asuka-culture",
        "title": "일본 쇼토쿠 태자의 아스카 문화 개창과 17조 헌법",
        "title_en": "Prince Shotoku: Asuka Culture, 17-Article Constitution & Horyu-ji",
        "region_id": "OTHER_REGIONS",
        "sub_region": "동아시아 / 일본",
        "category_id": "INSTITUTION",
        "importance": "A",
        "year_start": 593,
        "year_end": 622,
        "date_precision": "range",
        "summary": "백제·고구려의 불교·유교 문물을 적극 수용하여 관위 12계와 17조 헌법을 제정하고 호류사(법륭사)를 건립하여 고대 율령 국가 기틀 마련.",
        "detailed_description": "6세기 말 스이코 천황의 섭정으로 취임한 쇼토쿠 태자는 한반도 삼국(특히 백제 혜총, 고구려 혜자 등 승려·학자)의 선진 문물을 대대적으로 도입하여 아스카 문화를 꽃피웠습니다.\n\n가문 혈통 대신 개인의 능력과 공적에 따라 관직을 부여하는 '관위 12계'를 제정하고, 604년 화합(和)과 불교·유교적 도덕률을 강조한 '17조 헌법'을 반포하여 천황 중심의 중앙집권적 국가 체제를 지향하였습니다. 현존하는 세계 최고(最古)의 목조 건축물인 호류사(法隆寺)와 사천왕사를 건립하여 불교를 국가 통치의 지도 이념으로 확립하였습니다.",
        "historical_significance": "일본 고대 국가 형성을 알리는 최초의 성문 규범과 불교 율령 문화의 개막.",
        "cause": "소가씨 등 유력 호족 세력 억제와 삼국 선진 도래인 기술 수용.",
        "consequence": "645년 다이카 개신과 나라 시대 율령 국가로의 결정적 도약.",
        "confidence": "HIGH",
        "sources": [{"title": "A History of Japan (G. B. Sansom)"}]
    },
    {
        "id": "global-islam-house-of-wisdom-baghdad",
        "title": "이슬람 황금기와 바그다드 지혜의 집(Bayt al-Hikma) 학문 융합",
        "title_en": "Islamic Golden Age & the House of Wisdom in Baghdad",
        "region_id": "OTHER_REGIONS",
        "sub_region": "중동 / 이라크",
        "category_id": "SCIENCE",
        "importance": "A",
        "year_start": 786,
        "year_end": 1258,
        "date_precision": "range",
        "summary": "아바스 왕조 하룬 알라시드와 알마문 치세에 그리스·인도·페르시아 고전을 아랍어로 번역하고 대수학(알콰리즈미), 의학(이븐 시나), 광학을 혁신.",
        "detailed_description": "8세기 후반 바그다드를 수도로 삼은 아바스 왕조는 전 세계 학자들을 초빙하여 대규모 번역 연구 기관인 '지혜의 집(House of Wisdom)'을 설립하였습니다.\n\n그리스의 아리스토텔레스·유클리드, 인도의 0과 십진법 수학, 페르시아의 천문학 서적을 아랍어로 집대성하는 '번역 운동(Translation Movement)'을 전개하였습니다. 알콰리즈미는 1·2차 방정식을 체계화하여 '대수학(Algebra)'을 창시하였고, 이븐 시나(아비센나)는 근대 의학의 표준서인 《의학정전(The Canon of Medicine)》을 저술하였으며, 이븐 알하이삼은 현대 광학의 기초를 놓았습니다.\n\n이슬람 황금기의 과학과 철학적 성취는 12세기 스페인 톨레도와 이탈리아 시칠리아를 통해 라틴어로 재번역되어 유럽 르네상스를 촉발한 결정적 원동력이 되었습니다.",
        "historical_significance": "동서양 고대 지식을 보존·융합하고 근대 과학의 방법론적 토대를 놓은 인류 지성사의 황금기.",
        "cause": "동서 무역로의 통합, 제지술 도입에 따른 서적 대량 보급, 학문에 대한 칼리프들의 전폭적 후원.",
        "consequence": "유럽 12세기 르네상스 촉발, 현대 수학·의학·천문학의 기초 확립.",
        "confidence": "HIGH",
        "sources": [{"title": "The House of Wisdom (Jim Al-Khalili)"}]
    },
    {
        "id": "global-srivijaya-maritime-empire",
        "title": "스리비자야 왕국(Srivijaya)의 말라카 해협 해상 패권과 해양 실크로드",
        "title_en": "Srivijaya Empire: Maritime Silk Road & Hegemony over Malacca Strait",
        "region_id": "OTHER_REGIONS",
        "sub_region": "동남아시아 / 인도네시아",
        "category_id": "ECONOMY",
        "importance": "A",
        "year_start": 650,
        "year_end": 1377,
        "date_precision": "range",
        "summary": "수마트라 팔렘방을 거점으로 당·송나라와 인도를 잇는 말라카 해협을 통제하며 향신료 무역과 대승불교 학술 중심지로 번영.",
        "detailed_description": "7세기 수마트라섬을 중심으로 발흥한 스리비자야는 말라카 해협과 순다 해협이라는 해양 실크로드의 절대 길목을 장악한 거대 해상 탈라소크라시(Thalassocracy) 제국이었습니다.\n\n당나라 승려 의정(義淨)이 인도 구법 여행 중 수년간 머물며 산스크리트어 경전을 번역할 정도로 1,000명이 넘는 승려가 수학하는 국제 불교 학문의 중심지였습니다. 육두구, 정향 등 몰루카 제도의 향신료와 백단향, 도자기, 비단을 독점 중계 무역하며 700년 이상 해양 아시아의 번영을 이끌었습니다.",
        "historical_significance": "동남아시아 최초의 대규모 해상 제국이자 해양 실크로드 국제 교역과 불교 문화의 허브.",
        "cause": "동서 해상 교역로(말라카 해협)의 지리적 독점과 강력한 해군력.",
        "consequence": "동남아 도서 지역의 불교·힌두 문화 융합 및 중세 아시아 해양 네트워크 완성.",
        "confidence": "HIGH",
        "sources": [{"title": "Early Kingdoms of the Indonesian Archipelago (Paul Michel Munoz)"}]
    },
    {
        "id": "global-khmer-angkor-wat",
        "title": "크메르 제국 수리야바르만 2세의 앙코르와트(Angkor Wat) 건설",
        "title_en": "Khmer Empire: Construction of Angkor Wat by Suryavarman II",
        "region_id": "OTHER_REGIONS",
        "sub_region": "동남아시아 / 캄보디아",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": 1113,
        "year_end": 1150,
        "date_precision": "range",
        "summary": "톤레사프호 수자원 관리 기반의 거대 농경 제국 크메르가 힌두교 비슈누 신과 신왕(Devaraja)의 영광을 위해 세계 최대 석조 사원 축조.",
        "detailed_description": "12세기 전반 앙코르 제국(크메르)의 전성기를 이끈 수리야바르만 2세는 수도 야소다라푸라에 면적 약 1.6㎢, 중앙 탑 높이 65m에 달하는 인류 최대의 단일 종교 석조 건축물인 앙코르와트를 건설하였습니다.\n\n힌두교 우주관에서 신들이 거처하는 메루산(수미산)을 형상화한 5개의 연꽃 봉우리 탑과 사원을 둘러싼 폭 190m의 거대한 해자는 고도의 토목 수리 공학을 보여줍니다. 외벽 회랑에는 800m에 걸쳐 《마하바라타》와 《라마야나》의 서사시, 우유 바다 젓기 신화, 왕의 행렬이 정교한 부조로 새겨져 있습니다.\n\n앙코르와트는 크메르인의 뛰어난 석조 건축술과 톤레사프호의 수문 제어 시스템이 결합된 중세 동남아시아 문명의 위대한 상징입니다.",
        "historical_significance": "단일 건축물 기준 세계 최대 규모의 석조 종교 유적이자 중세 동남아 힌두·불교 융합 문명의 정점.",
        "cause": "톤레사프 호수 범람을 활용한 3모작 벼농사 경제력과 신왕일치 이념의 종교적 과시.",
        "consequence": "동남아시아 전역에 걸친 크메르 문화적 패권 확립 및 이후 상좌부 불교 사원으로의 전환.",
        "confidence": "HIGH",
        "sources": [{"title": "Angkor and the Khmer Civilization (Michael D. Coe)"}]
    },
    {
        "id": "global-great-zimbabwe-stone-city",
        "title": "대짐바브웨(Great Zimbabwe) 거대 석조 도시와 인도양 금 무역",
        "title_en": "Great Zimbabwe: Monumental Dry-Stone Architecture & Indian Ocean Gold Trade",
        "region_id": "OTHER_REGIONS",
        "sub_region": "아프리카 / 짐바브웨",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": 1100,
        "year_end": 1450,
        "date_precision": "range",
        "summary": "모르타르 없이 화강암 블록을 정교하게 쌓아 올린 높이 11m의 '대성채(Great Enclosure)'와 인도양 스와힐리 금·상아 교역 번영.",
        "detailed_description": "11세기부터 쇼나족(Shona)이 건설한 대짐바브웨는 사하라 이남 아프리카에서 가장 규모가 큰 석조 도시 유적입니다.\n\n어떠한 접착제나 모르타르를 쓰지 않고 정밀하게 다듬은 화강암 벽돌만을 건식 공법(Dry Stone)으로 쌓아 올린 거대한 곡선형 외벽과 원추형 탑은 놀라운 건축 기술을 보여줍니다. 내륙의 풍부한 금광과 상아를 채굴하여 모잠비크 해안의 소팔라 항구를 통해 아라비아, 페르시아, 인도, 중국 명나라와 무역하였으며, 유적에서 중국 청자와 페르시아 유리병, 인도 구슬이 대량 출토되었습니다.",
        "historical_significance": "사하라 이남 아프리카 고유의 독창적 고도 석조 문명과 인도양 글로벌 해상 무역망의 실증 유적.",
        "cause": "금광 자원 독점과 소 방목 목축 경제, 인도양 해상 교역로의 연결.",
        "consequence": "쇼나 제국의 번영 및 오늘날 짐바브웨 국명의 기원이자 국가적 정체성 확립.",
        "confidence": "HIGH",
        "sources": [{"title": "Great Zimbabwe (Peter Garlake)"}]
    },
    {
        "id": "global-mali-mansa-musa-pilgrimage",
        "title": "말리 제국 만사 무사 황제의 메카 순례와 팀북투 학문 중심지 부흥",
        "title_en": "Mali Empire: Mansa Musa's Epic Hajj & Rise of Timbuktu",
        "region_id": "OTHER_REGIONS",
        "sub_region": "아프리카 / 말리",
        "category_id": "ECONOMY",
        "importance": "A",
        "year_start": 1324,
        "year_end": 1325,
        "date_precision": "range",
        "summary": "수만 명의 수행단과 수십 톤의 황금을 이끌고 카이로를 거쳐 메카를 순례하여 중동 금값을 폭락시키고 팀북투를 이슬람 학문·도서관 도시로 육성.",
        "detailed_description": "1324년 서아프리카 말리 제국의 황제 만사 무사(Mansa Musa)는 역사상 가장 화려하고 거대한 메카 순례(Hajj) 원정에 올랐습니다.\n\n수천 명의 호위병과 80마리의 낙타에 각각 130kg의 금괴를 싣고 카이로를 방문하여 아낌없이 황금을 나누어주었으며, 이로 인해 이집트와 지중해의 금값이 향후 10년 이상 폭락할 정도였습니다. 이 순례로 유럽 지도(카탈루냐 아틀라스)에 왕관과 금덩이를 든 '말리의 군주'로 명성을 떨쳤습니다.\n\n귀국 후 안달루시아 출신 건축가 아부 이스하크를 초빙하여 팀북투에 징가레베르 모스크와 산코레 마드라사(이슬람 대학)를 건립하여, 수십만 권의 아랍어 필사본이 보관된 아프리카 최고의 학문·무역 중심지로 도약시켰습니다.",
        "historical_significance": "인류 역사상 최대 부호의 국가적 위상 과시이자 서아프리카를 글로벌 이슬람 학문망의 중심으로 편입시킨 사건.",
        "cause": "밤부크와 부레의 막대한 사금 광산 독점과 사하라 종단 소금 무역망의 통제.",
        "consequence": "유럽인의 서아프리카 황금 탐험 촉발 및 팀북투의 세계적 이슬람 학술 도시 번영.",
        "confidence": "HIGH",
        "sources": [{"title": "The Golden Rhinoceros: Histories of the African Middle Ages"}]
    },

    # --- 3. 근세 & 대항해 시대 (AD 14C ~ AD 17C) ---
    {
        "id": "global-aztec-tenochtitlan-empire",
        "title": "아즈텍 제국(Aztec)의 테노치티틀란 건설과 멕시코 중원 통일",
        "title_en": "Aztec Empire: Founding of Tenochtitlan & Mesoamerican Hegemony",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 멕시코",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1325,
        "year_end": 1521,
        "date_precision": "range",
        "summary": "텍스코코 호수 한가운데 인공 수상 섬도시 테노치티틀란을 건설하고 치남파 수경 농업과 3국 동맹을 통해 500여 개 도시국가를 복속한 군사 제국 구축.",
        "detailed_description": "1325년 멕시카인들은 '선인장 위에 뱀을 물고 앉아 있는 독수리를 보는 곳에 도시를 세우라'는 태양신 우이칠로포치틀리의 신탁에 따라 텍스코코 호수 중앙에 테노치티틀란을 건설하였습니다.\n\n갈대와 흙을 엮어 호수 위에 만든 인공 섬 수경 밭인 '치남파(Chinampa)' 농법을 통해 20만 명이 넘는 인구를 부양하였으며, 제방과 수로, 도개교로 연결된 당대 세계 최대급의 수상 도시를 완성하였습니다. 텍스코코, 틀라코판과 3국 동맹을 맺고 강력한 재규어·독수리 전사단을 앞세워 멕시코 고원 대부분을 지배하는 대제국으로 성장하였습니다.\n\n거대 신전 템플로 마요르(Templo Mayor)를 중심으로 한 태양 유지 의식과 고도의 공물 징수 행정망을 구축하였습니다.",
        "historical_significance": "스페인 정복 이전 북미 대륙에서 가장 거대하고 번영했던 도시 제국 문명.",
        "cause": "호수 위 치남파 집약 농업의 폭발적 생산성과 3국 동맹의 군사 팽창.",
        "consequence": "1521년 코르테스의 침략으로 멸망 후 오늘날 멕시코시티의 지리적·문화적 모태 형성.",
        "confidence": "HIGH",
        "sources": [{"title": "The Aztecs (Richard F. Townsend)"}]
    },
    {
        "id": "global-inca-empire-machu-picchu",
        "title": "잉카 제국(Inca)의 안데스 통일과 마추픽추·카팍 냔(도로망) 건설",
        "title_en": "Inca Empire (Tawantinsuyu): Machu Picchu & the Qhapaq Ñan Road Network",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 페루",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1438,
        "year_end": 1533,
        "date_precision": "range",
        "summary": "파차쿠티 황제가 쿠스코를 중심으로 4천km 안데스 산맥을 잇는 제국 도로망(카팍 냔)과 결승문자(키푸), 공중요새 마추픽추 축조.",
        "detailed_description": "1438년 파차쿠티(Pachacuti) 황제의 즉위와 함께 '태양의 제국' 타완틴수유(Tawantinsuyu, 사방의 땅)로 불린 잉카 제국이 안데스 전역을 통일하였습니다.\n\n해발 2,430m 절벽 위에 모르타르 없이 수십 톤의 화강암을 1mm 오차도 없이 맞물려 지은 공중 도시 마추픽추와 쿠스코의 사크사이우아만 요새는 인류 석조 공학의 정수입니다. 문자와 철기, 바퀴 없이도 매듭의 색상과 꼬임으로 세금과 인구를 기록한 '키푸(Quipu)' 시스템과 4만km에 달하는 고산 도로망 '카팍 냔(Qhapaq Ñan)', 파발꾼 차스키(Chasqui)를 통해 광대한 제국을 완벽히 통치하였습니다.\n\n안데스 산비탈의 계단식 밭(안데네스)과 콜카(곡물 창고)를 통한 사회주의적 재분배 복지 제도를 운영하였습니다.",
        "historical_significance": "신대륙 최대 영토를 자랑한 고대 안데스 사회공학 및 석조 토목 문명의 결정체.",
        "cause": "파차쿠티의 정복 사업과 미타(Mita) 공동 노동 제도 기반의 거대 토목 공사 집행력.",
        "consequence": "남미 안데스 문화의 통일적 기반 완성 및 피사로 정복 이후 안데스 전통의 지속.",
        "confidence": "HIGH",
        "sources": [{"title": "The Last Days of the Incas (Kim MacQuarrie)"}]
    },
    {
        "id": "global-ottoman-conquest-constantinople",
        "title": "오스만 제국 메흐메트 2세의 콘스탄티노플 정복과 동서 교역로 통제",
        "title_en": "Fall of Constantinople to Mehmed II & Ottoman Empire Dominance",
        "region_id": "OTHER_REGIONS",
        "sub_region": "중동·아나톨리아 / 튀르키예",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1453,
        "year_end": 1453,
        "date_precision": "exact",
        "summary": "우르반의 거대 대포와 육로 함선 이동 작전으로 천년 비잔티움 제국을 멸망시키고 이스탄불 천도 및 유럽-아시아 3대륙 대제국 완성.",
        "detailed_description": "1453년 5월 29일, 21세의 젊은 술탄 메흐메트 2세가 이끄는 오스만 제국 군대가 난공불락으로 불리던 비잔티움 제국의 수도 콘스탄티노플을 함락시켰습니다.\n\n메흐메트 2세는 갈라타 언덕 너머로 하룻밤 사이에 70여 척의 함선을 굴려 골든혼만으로 진입시키는 기상천외한 전술과 거대한 '우르반 대포(Dardanelles Gun)'를 동원해 테오도시우스 3중 성벽을 파괴하였습니다. 하기아 소피아 성당을 모스크로 개조하고 도시 이름을 이스탄불로 개칭하여 제국의 수도로 삼았습니다.\n\n이 사건으로 동로마 제국이 천년 만에 최종 멸망하였으며, 오스만 제국이 지중해와 실크로드 육상 무역로를 장악하자 서유럽 국가들이 아프리카와 대서양을 우회하는 신항로 개척(대항해 시대)에 나서는 결정적 계기가 되었습니다.",
        "historical_significance": "중세의 종말과 근대 개막을 알리는 세계사 최대 분기점이자 유럽 대항해 시대의 도화선.",
        "cause": "오스만 화약 군대의 기술적 우위와 비잔티움 제국의 오랜 쇠퇴.",
        "consequence": "동로마 학자들의 이탈리아 망명으로 르네상스 촉진, 서유럽의 신항로 개척 촉발.",
        "confidence": "HIGH",
        "sources": [{"title": "1453: The Holy War for Constantinople (Roger Crowley)"}]
    },
    {
        "id": "global-mughal-empire-akbar",
        "title": "무굴 제국(Mughal) 악바르 대제의 종교 융합과 타지마할 건축 황금기",
        "title_en": "Mughal Empire: Akbar's Religious Tolerance & Golden Age of Taj Mahal",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "ART_CULTURE",
        "importance": "A",
        "year_start": 1526,
        "year_end": 1707,
        "date_precision": "range",
        "summary": "티무르의 후예 바부르가 인도에 건국 후, 악바르 대제가 지즈야(비이슬람교도 인두세)를 폐지하고 인도·이슬람 융합 문화와 타지마할 건축 완성.",
        "detailed_description": "1526년 바부르가 파니파트 전투에서 승리하며 세운 무굴 제국은 제3대 악바르 대제(Akbar the Great) 시기에 인도 아대륙 대부분을 장악하며 전성기를 맞았습니다.\n\n악바르는 다수인 힌두교도와의 화합을 위해 비이슬람세(지즈야)를 과감히 폐지하고 라지푸트 공주와 혼인하였으며, 종교 간 토론의 장인 '이바다트 카나'를 열어 관용과 융합의 통치 철학을 구현하였습니다. 페르시아어, 아랍어, 힌디어가 융합된 우르두어(Urdu)가 탄생하였으며, 미니어처 회화와 직물 산업이 번영하였습니다.\n\n제5대 샤 자한 황제는 세상을 떠난 왕비 뭄타즈 마할을 추모하며 순백의 대리석 돔과 좌우대칭의 정원으로 이루어진 인류 건축의 보석 타지마할(Taj Mahal)을 완공하였습니다.",
        "historical_significance": "인도 힌두 문명과 이슬람 페르시아 문명이 찬란하게 융합된 근세 남아시아의 초강대국.",
        "cause": "화약 무기와 기병 전술의 우위, 악바르 대제의 과감한 종교 관용 및 토지 세제 개혁.",
        "consequence": "인도 전체 GDP가 세계 25%에 달하는 경제적 번영과 인도·이슬람 복합 문화의 완성.",
        "confidence": "HIGH",
        "sources": [{"title": "The Mughal Empire (John F. Richards)"}]
    },
    {
        "id": "global-potosi-silver-mine-global-economy",
        "title": "볼리비아 포토시(Potosí) 은광 발견과 글로벌 은 유통망 혁명",
        "title_en": "Discovery of Potosí Silver Mountain & Global Trade Revolution",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 볼리비아",
        "category_id": "ECONOMY",
        "importance": "A",
        "year_start": 1545,
        "year_end": 1650,
        "date_precision": "range",
        "summary": "안데스 해발 4,000m의 '은의 산(세로 리코)'에서 전 세계 은의 절반 이상을 채굴하여 마닐라 갤리온선을 통해 명나라와 유럽으로 공급, 세계 화폐 경제 통합.",
        "detailed_description": "1545년 볼리비아 고원의 세로 리코(Cerro Rico, 부유한 산)에서 인류 역사상 최대 규모의 은광이 발견되면서 포토시는 런던이나 파리보다 큰 인구 16만의 대도시로 급성장하였습니다.\n\n수은 아말감 제련법(파티오 공법)을 통해 매년 수백 톤의 은을 생산하였으며, 이 은은 스페인의 보물선단을 통해 유럽으로 운송되어 유럽 전역의 물가를 폭등시키는 '가격 혁명(Price Revolution)'을 일으켰습니다. 또한 멕시코 아카풀코에서 필리핀 마닐라를 오가는 '마닐라 갤리온 무역'을 통해 중국 명나라의 일조편법(은 본위 조세제도)과 직결되어 인류 최초의 진정한 지구적 화폐 유통망을 완성하였습니다.",
        "historical_significance": "아메리카의 은, 유럽의 상선, 아시아(중국)의 상품을 하나로 묶은 글로벌 자본주의의 탄생점.",
        "cause": "스페인 정복자들의 신대륙 자원 탐사와 원주민 미타 강제 노동 동원.",
        "consequence": "유럽 가격 혁명, 명·청나라의 은 본위 화폐 체제 확립, 대서양-태평양 삼각 무역 번영.",
        "confidence": "HIGH",
        "sources": [{"title": "Potosí: The Silver Mountain That Changed the World (Kris Lane)"}]
    },
    {
        "id": "global-japan-edo-shogunate",
        "title": "도쿠가와 이에야스의 에도 막부(Edo Shogunate) 개창과 260년 평화",
        "title_en": "Edo Shogunate Founded by Tokugawa Ieyasu: Pax Tokugawa & Chonin Culture",
        "region_id": "OTHER_REGIONS",
        "sub_region": "동아시아 / 일본",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1603,
        "year_end": 1867,
        "date_precision": "range",
        "summary": "세키가하라 전투 승리 후 에도(도쿄)에 막부를 열고, 참근교대제와 쇄국령(데지마 네덜란드 교역 예외)으로 260년간 내전 없는 상인(조닌) 문화 황금기 구현.",
        "detailed_description": "1600년 세키가하라 전투에서 승리한 도쿠가와 이에야스는 1603년 정이대장군(쇼군)에 취임하여 에도(현 도쿄)를 중심으로 강력한 중앙집권적 봉건 체제(막번 체제)를 수립하였습니다.\n\n다이묘들이 격년으로 에도와 영지를 오가게 한 '참근교대(산킨코타이)' 제도를 통해 지방 번의 반란을 억제하고 전국 도로망과 상업 유통을 폭발적으로 발전시켰습니다. 1630년대 기독교 확산을 막기 위해 쇄국령을 단행하되, 나가사키 데지마를 통해 네덜란드 및 청나라와 제한된 교역을 유지하며 난학(네덜란드 서양 학문)을 수용하였습니다.\n\n260년간 이어진 '도쿠가와의 평화(Pax Tokugawa)' 속에서 에도는 인구 100만의 세계 최대 도시로 성장하였으며, 가부키, 우키요에, 조루리 등 서민 상인 계층(조닌) 중심의 독창적인 문화가 만개하였습니다.",
        "historical_significance": "일본 근세 사회의 안정과 상업 경제의 비약적 발전, 메이지 유신으로 이어지는 근대화의 내적 축적기.",
        "cause": "센고쿠 시대 100년 내전의 종식과 철저한 막번 통제 및 신분제(사농공상) 확립.",
        "consequence": "조닌 문화와 난학의 발달, 상업 자본 축적으로 19세기 메이지 유신의 신속한 근대화 토대 마련.",
        "confidence": "HIGH",
        "sources": [{"title": "A History of Japan: Revised Edition (Conrad Totman)"}]
    },

    # --- 4. 근대 & 현대 (AD 18C ~ AD 21C) ---
    {
        "id": "global-latin-america-bolivar-independence",
        "title": "시몬 볼리바르의 라틴아메리카 해방 전쟁과 그란콜롬비아",
        "title_en": "Simón Bolívar & the Latin American Wars of Independence",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 베네수엘라·콜롬비아",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1810,
        "year_end": 1830,
        "date_precision": "range",
        "summary": "'해방자(El Libertador)' 시몬 볼리바르와 호세 데 산마르틴이 300년간의 스페인 식민 지배를 타파하고 남미 6개국 독립 쟁취.",
        "detailed_description": "19세기 초 나폴레옹의 스페인 침공으로 본국의 통치력이 약화되자, 라틴아메리카 태생 백인(크리오요)들을 중심으로 독립 혁명의 불길이 당겨졌습니다.\n\n'해방자' 시몬 볼리바르는 안데스 산맥을 넘는 대원정을 감행하여 보이아카 전투(1819)와 카라보보 전투(1821)에서 스페인 왕당파 군대를 격파하고 베네수엘라, 콜롬비아, 에콰도르, 파나마를 아우르는 연방 공화국 '그란콜롬비아(Gran Colombia)'를 수립하였습니다. 남쪽에서는 호세 데 산마르틴이 칠레와 페루를 해방시키고 볼리바르와 협력하여 1824년 아야쿠초 전투에서 남미의 스페인 식민 지배를 완전히 종식시켰습니다.\n\n볼리바르는 라틴아메리카 전체가 하나로 뭉치는 범아메리카 연방을 꿈꾸었으나, 지역주의와 군벌(카우디요) 간의 갈등으로 분열되었습니다.",
        "historical_significance": "남미 대륙 전체의 300년 스페인 식민 지배 종식과 근대 민족 공화국들의 독립.",
        "cause": "계몽주의 사상, 미국·프랑스 혁명의 영향, 크리오요의 정치적 차별에 대한 저항.",
        "consequence": "베네수엘라, 콜롬비아, 페루, 에콰도르, 볼리비아 등 주권 독립 국가 탄생.",
        "confidence": "HIGH",
        "sources": [{"title": "Bolivar: American Liberator (Marie Arana)"}]
    },
    {
        "id": "global-japan-meiji-restoration",
        "title": "일본 메이지 유신(Meiji Restoration)과 근대 국가 전환",
        "title_en": "Meiji Restoration: Abolition of Feudalism & Rapid Modernization",
        "region_id": "OTHER_REGIONS",
        "sub_region": "동아시아 / 일본",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1868,
        "year_end": 1890,
        "date_precision": "range",
        "summary": "에도 막부를 타도하고 천황 중심의 중앙집권적 근대 국가를 수립하여 폐번치현, 신분제 폐지, 징병제, 헌법 제정 및 산업혁명 단행.",
        "detailed_description": "1853년 미국 페리 제독의 흑선(쿠로후네) 내항 이후 굴욕적인 불평등 조약을 맺은 일본은 사쓰마와 조슈 번의 하급 무사들을 중심으로 '존황양이'와 '도막' 운동을 전개하여 1868년 에도 막부를 무너뜨리고 천황 정치를 복위시켰습니다.\n\n메이지 정부는 '문명개화', '부국강병', '식산흥업'을 3대 기치로 내걸고 봉건 번을 폐지하고 중앙 관료를 파견하는 폐번치현(1871), 신분제 철폐(사민평등), 근대적 토지조사 및 지조개정, 국민개병제(징병령)를 단행하였습니다. 이와쿠라 사절단을 구미 열강에 파견하여 서구의 법률, 과학, 군사, 교육 시스템을 전면 도입하였으며, 1889년 아시아 최초의 근대적 헌법인 《대일본제국 헌법》을 제정하였습니다.\n\n아시아에서 비서구 국가 최초로 산업혁명을 성공시키며 근대 국민국가로 탈바꿈하였으나, 군국주의와 대외 침략 노선으로 경도되는 양면성을 띠었습니다.",
        "historical_significance": "아시아 최초의 서구식 근대 국가 전환이자 산업혁명 성공 모델.",
        "cause": "서구 열강의 개항 압력과 막부 봉건 체제의 모순, 개혁 관료들의 부국강병 의지.",
        "consequence": "아시아 열강으로의 급부상, 동아시아 세력 균형 재편 및 청일·러일 전쟁 발발.",
        "confidence": "HIGH",
        "sources": [{"title": "The Making of Modern Japan (Marius B. Jansen)"}]
    },
    {
        "id": "global-mexican-revolution-zapata",
        "title": "멕시코 혁명(Mexican Revolution)과 에밀리아노 사파타의 토지 개혁",
        "title_en": "Mexican Revolution & Emiliano Zapata's Agrarian Reform",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 멕시코",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1910,
        "year_end": 1920,
        "date_precision": "range",
        "summary": "디아스 독재에 맞서 '토지와 자유(Tierra y Libertad)'를 외친 농민군과 마데로, 판초 비야 등이 10년간 투쟁하여 라틴아메리카 최초의 진보적 헌법(1917) 제정.",
        "detailed_description": "1910년 30년 넘게 이어진 포르피리오 디아스의 독재와 대토지 소유제(하시엔다)에 저항하여 라틴아메리카 최초의 거대한 민중 사회 혁명이 폭발하였습니다.\n\n남부의 농민 지도자 에밀리아노 사파타는 아얄라 계획을 선포하고 '토지는 일구는 자의 것'이라는 구호 아래 공유지(에히도) 복원을 요구하였으며, 북부에서는 판초 비야가 이끄는 기마군단이 혁명에 가세하였습니다. 10년간 100만 명 이상이 희생된 격렬한 내전 끝에 1917년 헌법이 공포되었으며, 이는 노동권, 8시간 노동제, 무상 초등교육, 천연자원의 국유화 및 토지 개혁을 세계 최초로 명문화한 진보적 헌법이었습니다.",
        "historical_significance": "20세기 세계 최초의 사회적 권리 헌법을 탄생시킨 라틴아메리카 현대사의 분수령.",
        "cause": "하시엔다 대토지 독점, 농민 수탈, 외세 자본 결탁에 대한 광범위한 민중 분노.",
        "consequence": "라틴아메리카 전역에 토지 개혁과 민족주의 운동 확산, 현대 멕시코 제도의 기틀 마련.",
        "confidence": "HIGH",
        "sources": [{"title": "The Mexican Revolution (Alan Knight)"}]
    },
    {
        "id": "global-india-gandhi-independence",
        "title": "마하트마 간디의 비폭력 불복종(사티아그라하)과 인도 독립",
        "title_en": "Mahatma Gandhi's Satyagraha, Salt March & Indian Independence",
        "region_id": "OTHER_REGIONS",
        "sub_region": "남아시아 / 인도",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1930,
        "year_end": 1947,
        "date_precision": "range",
        "summary": "영국의 가혹한 식민 지배에 맞서 400km '소금 행진'과 물레 돌리기 등 비폭력 저항(사티아그라하)을 이끌며 200년 만에 인도 독립 쟁취.",
        "detailed_description": "20세기 초 영국의 식민 통치에 맞서 마하트마 간디(Mahatma Gandhi)는 진리의 파지(사티아그라하)와 아힘사(비폭력)를 핵심 철학으로 내세워 인도 국민회의를 이끌었습니다.\n\n1930년 영국의 소금 전매법과 무거운 세금에 항의하여 78명의 지지자들과 함께 아마다바드에서 단디 해안까지 390km를 도보로 행진한 '소금 행진(Salt March)'은 전 인도 민중의 자각과 거대한 불복종 운동을 촉발하였습니다. 영국산 직물 수입을 거부하고 전통 물레(차르카)로 직접 옷을 지어 입는 스와데시(국산품 애용) 운동을 전개하여 식민 경제의 착취 구조를 흔들었습니다.\n\n간디의 비폭력 평화주의는 1947년 8월 15일 영국의 200년 식민 지배를 끝내고 인도의 주권 독립을 이끌어냈으며, 마틴 루서 킹의 미국 흑인 민권 운동과 넬슨 만델라의 반아파르트헤이트 운동 등 20세기 인류 평화 인권 운동의 영원한 나침반이 되었습니다.",
        "historical_significance": "무력과 폭력 없이 제국주의를 무너뜨린 20세기 인류 비폭력 평화 저항의 최고봉.",
        "cause": "영국의 가혹한 식민지 경제 수탈과 암리차르 학살 등 인권 탄압에 대한 민족적 저항.",
        "consequence": "1947년 인도 및 파키스탄 분리 독립 달성, 글로벌 탈식민지 독립 운동의 기폭제.",
        "confidence": "HIGH",
        "sources": [{"title": "Gandhi: An Autobiography (M. K. Gandhi)"}]
    },
    {
        "id": "global-cuba-revolution-castro-guevara",
        "title": "쿠바 혁명(Cuban Revolution)과 라틴아메리카 탈냉전 반제국주의",
        "title_en": "Cuban Revolution: Fidel Castro, Che Guevara & Socialism in the Americas",
        "region_id": "OTHER_REGIONS",
        "sub_region": "라틴아메리카 / 쿠바",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1953,
        "year_end": 1959,
        "date_precision": "range",
        "summary": "피델 카스트로와 체 게바라가 시에라 마에스트라 산맥에서 게릴라전을 전개하여 바티스타 친미 독재를 무너뜨리고 아메리카 대륙 최초의 사회주의 국가 수립.",
        "detailed_description": "1953년 몬카다 병영 습격을 시작으로 피델 카스트로, 라울 카스트로, 에르네스토 '체' 게바라는 7월 26일 운동을 결성하고 시에라 마에스트라 산악 지대에서 게릴라전을 펼쳤습니다.\n\n1959년 1월 1일 미국의 비호를 받던 바티스타 독재 정권을 최종 전복하고 아바나에 입성하여 아메리카 대륙 최초의 사회주의 공화국을 수립하였습니다. 토지 개혁, 문맹 퇴치 운동, 무상 의료 시스템을 전면 도입하였으며, 1961년 피그스만 침공 격퇴와 1962년 쿠바 미사일 위기를 거치며 냉전 시기 미국과 소련 대결의 최전선이자 제3세계 비동맹 운동의 거점으로 부상하였습니다.",
        "historical_significance": "미국의 뒷마당으로 불리던 라틴아메리카에서 일어난 탈냉전·사회주의 혁명이자 글로벌 게릴라 투쟁의 아이콘.",
        "cause": "바티스타 군사 독재의 부패와 미국 자본의 쿠바 설탕·도박 산업 독점에 대한 반발.",
        "consequence": "라틴아메리카 전역에 좌파 민족주의 운동 확산 및 쿠바 미사일 위기 촉발.",
        "confidence": "HIGH",
        "sources": [{"title": "Che Guevara: A Revolutionary Life (Jon Lee Anderson)"}]
    },
    {
        "id": "global-south-africa-mandela-apartheid",
        "title": "넬슨 만델라의 아파르트헤이트(인종격리) 철폐와 남아공 민주화",
        "title_en": "Nelson Mandela: Fall of Apartheid & Non-Racial Democratic South Africa",
        "region_id": "OTHER_REGIONS",
        "sub_region": "아프리카 / 남아프리카공화국",
        "category_id": "POLITICS",
        "importance": "A",
        "year_start": 1990,
        "year_end": 1994,
        "date_precision": "range",
        "summary": "27년간의 옥고 끝에 석방된 넬슨 만델라가 백인 정권과 협력하여 잔혹한 흑백 인종격리(아파르트헤이트)를 철폐하고 남아공 최초의 흑인 대통령에 당선.",
        "detailed_description": "1948년부터 남아프리카공화국 백인 정권은 흑인과 유색인종의 거주지, 교육, 참정권을 극단적으로 박탈하는 제도적 인종격리 정책인 '아파르트헤이트(Apartheid)'를 시행하였습니다.\n\n아프리카민족회의(ANC)를 이끌며 무장 투쟁을 전개하다 1964년 종신형을 선고받은 넬슨 만델라는 로벤섬 등에서 27년간 수감 생활을 하면서도 인종 화해와 인권의 상징으로 전 세계의 지지를 모았습니다. 국제사회의 경제 제재와 남아공 민중의 저항 속에 1990년 F.W. 데 클레르크 대통령에 의해 석방되었습니다.\n\n만델라는 백인에 대한 보복 대신 용서와 화해를 주창하며 평화적인 헌법 개정을 이끌어냈고, 1994년 전 인종이 참여한 역사상 최초의 민주 총선에서 남아공 최초의 흑인 대통령으로 당선되었습니다. 데즈먼드 투투 대주교와 함께 '진실화해위원회(TRC)'를 설치하여 피 흘림 없는 민주적 정권 교체와 국가 통합의 기적을 완성하였습니다.",
        "historical_significance": "20세기 최악의 제도적 인종차별 정책을 평화와 화해로 종식시킨 인류 도덕적 승리의 상징.",
        "cause": "아파르트헤이트의 반인도적 잔학성에 대한 국내외적 저항과 국제사회의 전방위적 제재.",
        "consequence": "다인종 민주주의 '무지개 국가' 남아공 출범 및 글로벌 진실화해 모델 정립.",
        "confidence": "HIGH",
        "sources": [{"title": "Long Walk to Freedom (Nelson Mandela)"}]
    }
]

def main():
    if not os.path.exists(SEED_FILE):
        print(f"Error: {SEED_FILE} not found.")
        return

    with open(SEED_FILE, "r", encoding="utf-8") as f:
        existing_events = json.load(f)

    existing_map = {e["id"]: e for e in existing_events}

    for ge in GLOBAL_EVENTS:
        existing_map[ge["id"]] = ge

    # Convert back to list and sort by year_start
    final_events = list(existing_map.values())
    final_events.sort(key=lambda x: (x.get("year_start", 0), x.get("year_end", 0)))

    with open(SEED_FILE, "w", encoding="utf-8") as f:
        json.dump(final_events, f, ensure_ascii=False, indent=2)

    print(f"✅ Successfully updated dataset. Total events: {len(final_events)}")

if __name__ == "__main__":
    main()
